/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { Client } from '../../models/client';

export interface ApiClientIdGet$Json$Params {
  id: (number | string);
}

export function apiClientIdGet$Json(http: HttpClient, rootUrl: string, params: ApiClientIdGet$Json$Params, context?: HttpContext): Observable<StrictHttpResponse<Client>> {
  const rb = new RequestBuilder(rootUrl, apiClientIdGet$Json.PATH, 'get');
  if (params) {
    rb.path('id', params.id, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'text/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Client>;
    })
  );
}

apiClientIdGet$Json.PATH = '/api/Client/{id}';
