/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ProjectTask } from '../../models/project-task';

export interface ApiProjectTaskPost$Plain$Params {
      body: ProjectTask
}

export function apiProjectTaskPost$Plain(http: HttpClient, rootUrl: string, params: ApiProjectTaskPost$Plain$Params, context?: HttpContext): Observable<StrictHttpResponse<ProjectTask>> {
  const rb = new RequestBuilder(rootUrl, apiProjectTaskPost$Plain.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/*+json');
  }

  return http.request(
    rb.build({ responseType: 'text', accept: 'text/plain', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ProjectTask>;
    })
  );
}

apiProjectTaskPost$Plain.PATH = '/api/ProjectTask';
