/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { RolePermissionDto } from '../../models/role-permission-dto';

export interface ApiRoleIdPermissionsPut$Plain$Params {
  id: (number | string);
      body: Array<RolePermissionDto>
}

export function apiRoleIdPermissionsPut$Plain(http: HttpClient, rootUrl: string, params: ApiRoleIdPermissionsPut$Plain$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<RolePermissionDto>>> {
  const rb = new RequestBuilder(rootUrl, apiRoleIdPermissionsPut$Plain.PATH, 'put');
  if (params) {
    rb.path('id', params.id, {});
    rb.body(params.body, 'application/*+json');
  }

  return http.request(
    rb.build({ responseType: 'text', accept: 'text/plain', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<RolePermissionDto>>;
    })
  );
}

apiRoleIdPermissionsPut$Plain.PATH = '/api/Role/{id}/permissions';
