/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { Role } from '../../models/role';

export interface ApiRoleByNameRoleNameGet$Plain$Params {
  roleName: string;
}

export function apiRoleByNameRoleNameGet$Plain(http: HttpClient, rootUrl: string, params: ApiRoleByNameRoleNameGet$Plain$Params, context?: HttpContext): Observable<StrictHttpResponse<Role>> {
  const rb = new RequestBuilder(rootUrl, apiRoleByNameRoleNameGet$Plain.PATH, 'get');
  if (params) {
    rb.path('roleName', params.roleName, {});
  }

  return http.request(
    rb.build({ responseType: 'text', accept: 'text/plain', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Role>;
    })
  );
}

apiRoleByNameRoleNameGet$Plain.PATH = '/api/Role/by-name/{roleName}';
