/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ReviewNoteRequest } from '../../models/review-note-request';
import { TimeEntryCorrectionRequest } from '../../models/time-entry-correction-request';

export interface ApiTimeEntryCorrectionRequestIdRejectPut$Plain$Params {
  id: (number | string);
      body: ReviewNoteRequest
}

export function apiTimeEntryCorrectionRequestIdRejectPut$Plain(http: HttpClient, rootUrl: string, params: ApiTimeEntryCorrectionRequestIdRejectPut$Plain$Params, context?: HttpContext): Observable<StrictHttpResponse<TimeEntryCorrectionRequest>> {
  const rb = new RequestBuilder(rootUrl, apiTimeEntryCorrectionRequestIdRejectPut$Plain.PATH, 'put');
  if (params) {
    rb.path('id', params.id, {});
    rb.body(params.body, 'application/*+json');
  }

  return http.request(
    rb.build({ responseType: 'text', accept: 'text/plain', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<TimeEntryCorrectionRequest>;
    })
  );
}

apiTimeEntryCorrectionRequestIdRejectPut$Plain.PATH = '/api/TimeEntryCorrectionRequest/{id}/reject';
