/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { TimeEntryCorrectionRequest } from '../../models/time-entry-correction-request';

export interface ApiTimeEntryCorrectionRequestIdGet$Plain$Params {
  id: (number | string);
}

export function apiTimeEntryCorrectionRequestIdGet$Plain(http: HttpClient, rootUrl: string, params: ApiTimeEntryCorrectionRequestIdGet$Plain$Params, context?: HttpContext): Observable<StrictHttpResponse<TimeEntryCorrectionRequest>> {
  const rb = new RequestBuilder(rootUrl, apiTimeEntryCorrectionRequestIdGet$Plain.PATH, 'get');
  if (params) {
    rb.path('id', params.id, {});
  }

  return http.request(
    rb.build({ responseType: 'text', accept: 'text/plain', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<TimeEntryCorrectionRequest>;
    })
  );
}

apiTimeEntryCorrectionRequestIdGet$Plain.PATH = '/api/TimeEntryCorrectionRequest/{id}';
