/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { CorrectionRequestDto } from '../../models/correction-request-dto';

export interface ApiTimeEntryCorrectionRequestMineGet$Plain$Params {
}

export function apiTimeEntryCorrectionRequestMineGet$Plain(http: HttpClient, rootUrl: string, params?: ApiTimeEntryCorrectionRequestMineGet$Plain$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<CorrectionRequestDto>>> {
  const rb = new RequestBuilder(rootUrl, apiTimeEntryCorrectionRequestMineGet$Plain.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'text', accept: 'text/plain', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<CorrectionRequestDto>>;
    })
  );
}

apiTimeEntryCorrectionRequestMineGet$Plain.PATH = '/api/TimeEntryCorrectionRequest/mine';
