/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { TimeEntryCorrectionRequest } from '../../models/time-entry-correction-request';

export interface ApiTimeEntryCorrectionRequestGet$Plain$Params {
}

export function apiTimeEntryCorrectionRequestGet$Plain(http: HttpClient, rootUrl: string, params?: ApiTimeEntryCorrectionRequestGet$Plain$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<TimeEntryCorrectionRequest>>> {
  const rb = new RequestBuilder(rootUrl, apiTimeEntryCorrectionRequestGet$Plain.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'text', accept: 'text/plain', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<TimeEntryCorrectionRequest>>;
    })
  );
}

apiTimeEntryCorrectionRequestGet$Plain.PATH = '/api/TimeEntryCorrectionRequest';
