/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { WorkSchedule } from '../../models/work-schedule';
import { WorkScheduleUpsertRequest } from '../../models/work-schedule-upsert-request';

export interface ApiWorkScheduleIdPut$Plain$Params {
  id: (number | string);
      body: WorkScheduleUpsertRequest
}

export function apiWorkScheduleIdPut$Plain(http: HttpClient, rootUrl: string, params: ApiWorkScheduleIdPut$Plain$Params, context?: HttpContext): Observable<StrictHttpResponse<WorkSchedule>> {
  const rb = new RequestBuilder(rootUrl, apiWorkScheduleIdPut$Plain.PATH, 'put');
  if (params) {
    rb.path('id', params.id, {});
    rb.body(params.body, 'application/*+json');
  }

  return http.request(
    rb.build({ responseType: 'text', accept: 'text/plain', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<WorkSchedule>;
    })
  );
}

apiWorkScheduleIdPut$Plain.PATH = '/api/WorkSchedule/{id}';
