/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { WorkSchedule } from '../../models/work-schedule';

export interface ApiWorkScheduleManagedGet$Plain$Params {
}

export function apiWorkScheduleManagedGet$Plain(http: HttpClient, rootUrl: string, params?: ApiWorkScheduleManagedGet$Plain$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<WorkSchedule>>> {
  const rb = new RequestBuilder(rootUrl, apiWorkScheduleManagedGet$Plain.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'text', accept: 'text/plain', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<WorkSchedule>>;
    })
  );
}

apiWorkScheduleManagedGet$Plain.PATH = '/api/WorkSchedule/managed';
