/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { WorkSchedule } from '../../models/work-schedule';

export interface ApiWorkSchedulePost$Json$Params {
      body: WorkSchedule
}

export function apiWorkSchedulePost$Json(http: HttpClient, rootUrl: string, params: ApiWorkSchedulePost$Json$Params, context?: HttpContext): Observable<StrictHttpResponse<WorkSchedule>> {
  const rb = new RequestBuilder(rootUrl, apiWorkSchedulePost$Json.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/*+json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'text/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<WorkSchedule>;
    })
  );
}

apiWorkSchedulePost$Json.PATH = '/api/WorkSchedule';
