/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { Rule } from '../../models/rule';

export interface ApiRulePost$Plain$Params {
      body: Rule
}

export function apiRulePost$Plain(http: HttpClient, rootUrl: string, params: ApiRulePost$Plain$Params, context?: HttpContext): Observable<StrictHttpResponse<Rule>> {
  const rb = new RequestBuilder(rootUrl, apiRulePost$Plain.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/*+json');
  }

  return http.request(
    rb.build({ responseType: 'text', accept: 'text/plain', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Rule>;
    })
  );
}

apiRulePost$Plain.PATH = '/api/Rule';
