/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { Notification } from '../../models/notification';

export interface ApiNotificationIdGet$Plain$Params {
  id: (number | string);
}

export function apiNotificationIdGet$Plain(http: HttpClient, rootUrl: string, params: ApiNotificationIdGet$Plain$Params, context?: HttpContext): Observable<StrictHttpResponse<Notification>> {
  const rb = new RequestBuilder(rootUrl, apiNotificationIdGet$Plain.PATH, 'get');
  if (params) {
    rb.path('id', params.id, {});
  }

  return http.request(
    rb.build({ responseType: 'text', accept: 'text/plain', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Notification>;
    })
  );
}

apiNotificationIdGet$Plain.PATH = '/api/Notification/{id}';
