/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { InviteUserRequest } from '../../models/invite-user-request';
import { InviteUserResponse } from '../../models/invite-user-response';

export interface ApiUserInvitationPost$Plain$Params {
      body: InviteUserRequest
}

export function apiUserInvitationPost$Plain(http: HttpClient, rootUrl: string, params: ApiUserInvitationPost$Plain$Params, context?: HttpContext): Observable<StrictHttpResponse<InviteUserResponse>> {
  const rb = new RequestBuilder(rootUrl, apiUserInvitationPost$Plain.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/*+json');
  }

  return http.request(
    rb.build({ responseType: 'text', accept: 'text/plain', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<InviteUserResponse>;
    })
  );
}

apiUserInvitationPost$Plain.PATH = '/api/UserInvitation';
