/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { UserInvitation } from '../../models/user-invitation';

export interface ApiUserInvitationGet$Plain$Params {
}

export function apiUserInvitationGet$Plain(http: HttpClient, rootUrl: string, params?: ApiUserInvitationGet$Plain$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<UserInvitation>>> {
  const rb = new RequestBuilder(rootUrl, apiUserInvitationGet$Plain.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'text', accept: 'text/plain', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<UserInvitation>>;
    })
  );
}

apiUserInvitationGet$Plain.PATH = '/api/UserInvitation';
