/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { TimeEntryBreak } from '../../models/time-entry-break';

export interface ApiTimeEntryIdBreaksBreakIdStopPut$Plain$Params {
  id: (number | string);
  breakId: (number | string);
}

export function apiTimeEntryIdBreaksBreakIdStopPut$Plain(http: HttpClient, rootUrl: string, params: ApiTimeEntryIdBreaksBreakIdStopPut$Plain$Params, context?: HttpContext): Observable<StrictHttpResponse<TimeEntryBreak>> {
  const rb = new RequestBuilder(rootUrl, apiTimeEntryIdBreaksBreakIdStopPut$Plain.PATH, 'put');
  if (params) {
    rb.path('id', params.id, {});
    rb.path('breakId', params.breakId, {});
  }

  return http.request(
    rb.build({ responseType: 'text', accept: 'text/plain', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<TimeEntryBreak>;
    })
  );
}

apiTimeEntryIdBreaksBreakIdStopPut$Plain.PATH = '/api/TimeEntry/{id}/breaks/{breakId}/stop';
