/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { TimeEntry } from '../../models/time-entry';

export interface ApiTimeEntryMineGet$Json$Params {
}

export function apiTimeEntryMineGet$Json(http: HttpClient, rootUrl: string, params?: ApiTimeEntryMineGet$Json$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<TimeEntry>>> {
  const rb = new RequestBuilder(rootUrl, apiTimeEntryMineGet$Json.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'text/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<TimeEntry>>;
    })
  );
}

apiTimeEntryMineGet$Json.PATH = '/api/TimeEntry/mine';
