/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { TimeEntry } from '../../models/time-entry';

export interface ApiTimeEntryIdStopPost$Json$Params {
  id: (number | string);
}

export function apiTimeEntryIdStopPost$Json(http: HttpClient, rootUrl: string, params: ApiTimeEntryIdStopPost$Json$Params, context?: HttpContext): Observable<StrictHttpResponse<TimeEntry>> {
  const rb = new RequestBuilder(rootUrl, apiTimeEntryIdStopPost$Json.PATH, 'post');
  if (params) {
    rb.path('id', params.id, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'text/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<TimeEntry>;
    })
  );
}

apiTimeEntryIdStopPost$Json.PATH = '/api/TimeEntry/{id}/stop';
