/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { BreakStartRequest } from '../../models/break-start-request';
import { TimeEntryBreak } from '../../models/time-entry-break';

export interface ApiTimeEntryIdBreaksPost$Plain$Params {
  id: (number | string);
      body: BreakStartRequest
}

export function apiTimeEntryIdBreaksPost$Plain(http: HttpClient, rootUrl: string, params: ApiTimeEntryIdBreaksPost$Plain$Params, context?: HttpContext): Observable<StrictHttpResponse<TimeEntryBreak>> {
  const rb = new RequestBuilder(rootUrl, apiTimeEntryIdBreaksPost$Plain.PATH, 'post');
  if (params) {
    rb.path('id', params.id, {});
    rb.body(params.body, 'application/*+json');
  }

  return http.request(
    rb.build({ responseType: 'text', accept: 'text/plain', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<TimeEntryBreak>;
    })
  );
}

apiTimeEntryIdBreaksPost$Plain.PATH = '/api/TimeEntry/{id}/breaks';
