/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { TimeEntry } from '../../models/time-entry';

export interface ApiTimeEntryStartPost$Plain$Params {
}

export function apiTimeEntryStartPost$Plain(http: HttpClient, rootUrl: string, params?: ApiTimeEntryStartPost$Plain$Params, context?: HttpContext): Observable<StrictHttpResponse<TimeEntry>> {
  const rb = new RequestBuilder(rootUrl, apiTimeEntryStartPost$Plain.PATH, 'post');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'text', accept: 'text/plain', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<TimeEntry>;
    })
  );
}

apiTimeEntryStartPost$Plain.PATH = '/api/TimeEntry/start';
