/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface AuthResponse {
  email?: string;
  firstName?: string;
  lastName?: string;
  roles?: Array<string>;
  token?: string;
  userId?: (number | string);
}
