/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ApprovalStatus } from '../models/approval-status';
export interface CorrectionRequestDto {
  id?: (number | string);
  proposedEndTime?: (string | null);
  proposedStartTime?: (string | null);
  reason?: string;
  requestedAt?: string;
  requestedByUserId?: (number | string);
  requestedByUserName?: string;
  status?: ApprovalStatus;
  timeEntryEndTime?: (string | null);
  timeEntryId?: (number | string);
  timeEntryStartTime?: string;
}
