/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface CreateUserRequest {
  email?: string;
  firstName?: string;
  lastName?: string;
  managerId?: (number | string | null);
  password?: string;
  roleId?: (number | string);
  teamId?: (number | string | null);
}
