/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { LeaveBalance } from '../models/leave-balance';
import { LeaveRequest } from '../models/leave-request';
import { Notification } from '../models/notification';
import { Project } from '../models/project';
import { Role } from '../models/role';
import { Team } from '../models/team';
import { TimeEntry } from '../models/time-entry';
import { TimeEntryAuditLog } from '../models/time-entry-audit-log';
import { TimeEntryCorrectionRequest } from '../models/time-entry-correction-request';
import { UserInvitation } from '../models/user-invitation';
import { WorkSchedule } from '../models/work-schedule';
export interface EnrichedUserDto {
  auditLogsMade?: Array<TimeEntryAuditLog>;
  correctionRequestsReviewed?: Array<TimeEntryCorrectionRequest>;
  correctionRequestsSubmitted?: Array<TimeEntryCorrectionRequest>;
  createdAt?: string;
  email?: string;
  firstName?: string;
  id?: (number | string);
  invitationsSent?: Array<UserInvitation>;
  isActive?: boolean;
  isEmailVerified?: boolean;
  lastLogin?: string;
  lastName?: string;
  leaveBalances?: Array<LeaveBalance>;
  leaveRequestsReviewed?: Array<LeaveRequest>;
  leaveRequestsSubmitted?: Array<LeaveRequest>;
  managedTeams?: Array<Team>;
  notifications?: Array<Notification>;
  projects?: Array<Project>;
  roles?: Array<Role>;
  teams?: Array<Team>;
  timeEntries?: Array<TimeEntry>;
  workSchedules?: Array<WorkSchedule>;
}
