/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface InviteUserRequest {
  email?: string;
  managerId?: (number | string | null);
  roleId?: (number | string);
  sendEmail?: boolean;
  teamId?: (number | string | null);
}
