/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { LeaveType } from '../models/leave-type';
import { User } from '../models/user';
export interface LeaveBalance {
  allocatedDays?: (number | string);
  id?: (number | string);
  leaveType?: LeaveType;
  leaveTypeId?: (number | string);
  usedDays?: (number | string);
  user?: User;
  userId?: (number | string);
  year?: (number | string);
}
