/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { User } from '../models/user';
export interface Notification {
  createdAt?: string;
  id?: (number | string);
  isRead?: boolean;
  linkUrl?: (string | null);
  message?: string;
  user?: User;
  userId?: (number | string);
}
