/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Project } from '../models/project';
export interface ProjectTask {
  createdAt?: string;
  id?: (number | string);
  isActive?: boolean;
  project?: Project;
  projectId?: (number | string);
  taskName?: string;
}
