/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Client } from '../models/client';
export interface Project {
  client?: (null | Client);
  clientId?: (number | string | null);
  createdAt?: string;
  id?: (number | string);
  isActive?: boolean;
  projectDisplayName?: string;
  projectName?: string;
}
