/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { AuthResponse } from '../models/auth-response';
export interface RegisterResponse {
  auth?: (null | AuthResponse);
  message?: (string | null);
}
