/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { PermissionLevel } from '../models/permission-level';
import { PermissionResource } from '../models/permission-resource';
export interface RolePermissionDto {
  level?: PermissionLevel;
  resource?: PermissionResource;
}
