/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { RuleScope } from '../models/rule-scope';
import { RuleType } from '../models/rule-type';
export interface Rule {
  createdAt?: string;
  id?: (number | string);
  isActive?: boolean;
  scope?: RuleScope;
  targetId?: (number | string | null);
  type?: RuleType;
}
