/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface SmtpSettingsResponse {
  fromAddress?: (string | null);
  fromName?: (string | null);
  host?: (string | null);
  isConfigured?: boolean;
  port?: (number | string | null);
  useSsl?: (boolean | null);
  username?: (string | null);
}
