/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface SmtpSettingsRequest {
  fromAddress?: string;
  fromName?: string;
  host?: string;
  password?: (string | null);
  port?: (number | string);
  useSsl?: boolean;
  username?: string;
}
