/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface TimeEntryBreak {
  endTime?: (string | null);
  id?: (number | string);
  reason?: (string | null);
  startTime?: string;
  timeEntryId?: (number | string);
}
