/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ApprovalStatus } from '../models/approval-status';
import { TimeEntry } from '../models/time-entry';
import { User } from '../models/user';
export interface TimeEntryCorrectionRequest {
  id?: (number | string);
  proposedEndTime?: (string | null);
  proposedStartTime?: (string | null);
  reason?: string;
  requestedAt?: string;
  requestedByUser?: User;
  requestedByUserId?: (number | string);
  reviewedAt?: (string | null);
  reviewedByUser?: (null | User);
  reviewedByUserId?: (number | string | null);
  status?: ApprovalStatus;
  timeEntry?: TimeEntry;
  timeEntryId?: (number | string);
}
