/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { AuditAction } from '../models/audit-action';
import { TimeEntry } from '../models/time-entry';
import { User } from '../models/user';
export interface TimeEntryAuditLog {
  action?: AuditAction;
  changedByUser?: User;
  changedByUserId?: (number | string);
  fieldName?: (string | null);
  id?: (number | string);
  newValue?: (string | null);
  oldValue?: (string | null);
  timeEntry?: TimeEntry;
  timeEntryId?: (number | string);
  timestamp?: string;
}
