/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Project } from '../models/project';
import { ProjectTask } from '../models/project-task';
import { TimeEntryBreak } from '../models/time-entry-break';
import { TimeEntryStatus } from '../models/time-entry-status';
import { User } from '../models/user';
export interface TimeEntry {
  breaks?: Array<TimeEntryBreak>;
  createdAt?: string;
  description?: (string | null);
  endTime?: (string | null);
  id?: (number | string);
  project?: (null | Project);
  projectId?: (number | string | null);
  projectTask?: (null | ProjectTask);
  projectTaskId?: (number | string | null);
  startTime?: string;
  status?: TimeEntryStatus;
  user?: User;
  userId?: (number | string);
}
