/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface TimeEntryUpdateRequest {
  description?: (string | null);
  projectId?: (number | string | null);
  projectTaskId?: (number | string | null);
}
