/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface User {
  createdAt?: string;
  email?: string;
  firstName?: string;
  id?: (number | string);
  isActive?: boolean;
  isEmailVerified?: boolean;
  lastLogin?: string;
  lastName?: string;
  managerId?: (number | string | null);
  profilePictureUrl?: (string | null);
}
