/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { User } from '../models/user';
export interface UserInvitation {
  acceptedAt?: (string | null);
  code?: string;
  createdAt?: string;
  email?: string;
  expiresAt?: string;
  id?: (number | string);
  invitedByUser?: User;
  invitedByUserId?: (number | string);
  managerId?: (number | string | null);
  roleId?: (number | string);
  teamId?: (number | string | null);
}
