/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface WorkScheduleUpsertRequest {
  effectiveFrom?: string;
  effectiveTo?: (string | null);
  fridayHours?: (number | string);
  mondayHours?: (number | string);
  saturdayHours?: (number | string);
  sundayHours?: (number | string);
  thursdayHours?: (number | string);
  tuesdayHours?: (number | string);
  userId?: (number | string);
  wednesdayHours?: (number | string);
}
