/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { User } from '../models/user';
export interface WorkSchedule {
  effectiveFrom?: string;
  effectiveTo?: (string | null);
  fridayHours?: (number | string);
  id?: (number | string);
  mondayHours?: (number | string);
  saturdayHours?: (number | string);
  sundayHours?: (number | string);
  thursdayHours?: (number | string);
  tuesdayHours?: (number | string);
  user?: User;
  userId?: (number | string);
  wednesdayHours?: (number | string);
}
