/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { RolePermissionDto } from '../../models/role-permission-dto';

export interface ApiUserMePermissionsGet$Json$Params {
}

export function apiUserMePermissionsGet$Json(http: HttpClient, rootUrl: string, params?: ApiUserMePermissionsGet$Json$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<RolePermissionDto>>> {
  const rb = new RequestBuilder(rootUrl, apiUserMePermissionsGet$Json.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'text/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<RolePermissionDto>>;
    })
  );
}

apiUserMePermissionsGet$Json.PATH = '/api/User/me/permissions';
