/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { IFormFile } from '../../models/i-form-file';
import { User } from '../../models/user';

export interface ApiUserIdProfilePicturePost$Json$Params {
  id: (number | string);
      body: {
'file'?: IFormFile;
}
}

export function apiUserIdProfilePicturePost$Json(http: HttpClient, rootUrl: string, params: ApiUserIdProfilePicturePost$Json$Params, context?: HttpContext): Observable<StrictHttpResponse<User>> {
  const rb = new RequestBuilder(rootUrl, apiUserIdProfilePicturePost$Json.PATH, 'post');
  if (params) {
    rb.path('id', params.id, {});
    rb.body(params.body, 'multipart/form-data');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'text/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<User>;
    })
  );
}

apiUserIdProfilePicturePost$Json.PATH = '/api/User/{id}/profile-picture';
