/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { PublicHoliday } from '../../models/public-holiday';

export interface ApiPublicHolidayPost$Json$Params {
      body: PublicHoliday
}

export function apiPublicHolidayPost$Json(http: HttpClient, rootUrl: string, params: ApiPublicHolidayPost$Json$Params, context?: HttpContext): Observable<StrictHttpResponse<PublicHoliday>> {
  const rb = new RequestBuilder(rootUrl, apiPublicHolidayPost$Json.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/*+json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'text/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<PublicHoliday>;
    })
  );
}

apiPublicHolidayPost$Json.PATH = '/api/PublicHoliday';
