/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { PublicHoliday } from '../../models/public-holiday';

export interface ApiPublicHolidayGet$Json$Params {
}

export function apiPublicHolidayGet$Json(http: HttpClient, rootUrl: string, params?: ApiPublicHolidayGet$Json$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<PublicHoliday>>> {
  const rb = new RequestBuilder(rootUrl, apiPublicHolidayGet$Json.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'text/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<PublicHoliday>>;
    })
  );
}

apiPublicHolidayGet$Json.PATH = '/api/PublicHoliday';
