/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { LeaveType } from '../../models/leave-type';

export interface ApiLeaveTypeGet$Json$Params {
}

export function apiLeaveTypeGet$Json(http: HttpClient, rootUrl: string, params?: ApiLeaveTypeGet$Json$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<LeaveType>>> {
  const rb = new RequestBuilder(rootUrl, apiLeaveTypeGet$Json.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'text/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<LeaveType>>;
    })
  );
}

apiLeaveTypeGet$Json.PATH = '/api/LeaveType';
