/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { LeaveType } from '../../models/leave-type';

export interface ApiLeaveTypePost$Plain$Params {
      body: LeaveType
}

export function apiLeaveTypePost$Plain(http: HttpClient, rootUrl: string, params: ApiLeaveTypePost$Plain$Params, context?: HttpContext): Observable<StrictHttpResponse<LeaveType>> {
  const rb = new RequestBuilder(rootUrl, apiLeaveTypePost$Plain.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/*+json');
  }

  return http.request(
    rb.build({ responseType: 'text', accept: 'text/plain', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<LeaveType>;
    })
  );
}

apiLeaveTypePost$Plain.PATH = '/api/LeaveType';
