/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { SmtpSettingsRequest } from '../../models/smtp-settings-request';
import { SmtpSettingsResponse } from '../../models/smtp-settings-response';

export interface ApiSmtpSettingsPut$Json$Params {
      body: SmtpSettingsRequest
}

export function apiSmtpSettingsPut$Json(http: HttpClient, rootUrl: string, params: ApiSmtpSettingsPut$Json$Params, context?: HttpContext): Observable<StrictHttpResponse<SmtpSettingsResponse>> {
  const rb = new RequestBuilder(rootUrl, apiSmtpSettingsPut$Json.PATH, 'put');
  if (params) {
    rb.body(params.body, 'application/*+json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'text/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<SmtpSettingsResponse>;
    })
  );
}

apiSmtpSettingsPut$Json.PATH = '/api/SmtpSettings';
