/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { SmtpSettingsResponse } from '../../models/smtp-settings-response';

export interface ApiSmtpSettingsGet$Plain$Params {
}

export function apiSmtpSettingsGet$Plain(http: HttpClient, rootUrl: string, params?: ApiSmtpSettingsGet$Plain$Params, context?: HttpContext): Observable<StrictHttpResponse<SmtpSettingsResponse>> {
  const rb = new RequestBuilder(rootUrl, apiSmtpSettingsGet$Plain.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'text', accept: 'text/plain', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<SmtpSettingsResponse>;
    })
  );
}

apiSmtpSettingsGet$Plain.PATH = '/api/SmtpSettings';
