/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { firstValueFrom } from 'rxjs';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { apiAppSettingsGet$Json } from '../fn/app-settings/api-app-settings-get-json';
import { ApiAppSettingsGet$Json$Params } from '../fn/app-settings/api-app-settings-get-json';
import { apiAppSettingsGet$Plain } from '../fn/app-settings/api-app-settings-get-plain';
import { ApiAppSettingsGet$Plain$Params } from '../fn/app-settings/api-app-settings-get-plain';
import { apiAppSettingsPut$Json } from '../fn/app-settings/api-app-settings-put-json';
import { ApiAppSettingsPut$Json$Params } from '../fn/app-settings/api-app-settings-put-json';
import { apiAppSettingsPut$Plain } from '../fn/app-settings/api-app-settings-put-plain';
import { ApiAppSettingsPut$Plain$Params } from '../fn/app-settings/api-app-settings-put-plain';
import { AppSettingsResponse } from '../models/app-settings-response';

@Injectable({ providedIn: 'root' })
export class AppSettingsService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `apiAppSettingsGet()` */
  static readonly ApiAppSettingsGetPath = '/api/AppSettings';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiAppSettingsGet$Plain()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiAppSettingsGet$Plain$Response(params?: ApiAppSettingsGet$Plain$Params, context?: HttpContext): Promise<StrictHttpResponse<AppSettingsResponse>> {
    const obs = apiAppSettingsGet$Plain(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiAppSettingsGet$Plain$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiAppSettingsGet$Plain(params?: ApiAppSettingsGet$Plain$Params, context?: HttpContext): Promise<AppSettingsResponse> {
    const resp = this.apiAppSettingsGet$Plain$Response(params, context);
    return resp.then((r: StrictHttpResponse<AppSettingsResponse>): AppSettingsResponse => r.body);
  }

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiAppSettingsGet$Json()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiAppSettingsGet$Json$Response(params?: ApiAppSettingsGet$Json$Params, context?: HttpContext): Promise<StrictHttpResponse<AppSettingsResponse>> {
    const obs = apiAppSettingsGet$Json(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiAppSettingsGet$Json$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiAppSettingsGet$Json(params?: ApiAppSettingsGet$Json$Params, context?: HttpContext): Promise<AppSettingsResponse> {
    const resp = this.apiAppSettingsGet$Json$Response(params, context);
    return resp.then((r: StrictHttpResponse<AppSettingsResponse>): AppSettingsResponse => r.body);
  }

  /** Path part for operation `apiAppSettingsPut()` */
  static readonly ApiAppSettingsPutPath = '/api/AppSettings';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiAppSettingsPut$Plain()` instead.
   *
   * This method sends `application/*+json` and handles request body of type `application/*+json`.
   */
  apiAppSettingsPut$Plain$Response(params: ApiAppSettingsPut$Plain$Params, context?: HttpContext): Promise<StrictHttpResponse<AppSettingsResponse>> {
    const obs = apiAppSettingsPut$Plain(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiAppSettingsPut$Plain$Response()` instead.
   *
   * This method sends `application/*+json` and handles request body of type `application/*+json`.
   */
  apiAppSettingsPut$Plain(params: ApiAppSettingsPut$Plain$Params, context?: HttpContext): Promise<AppSettingsResponse> {
    const resp = this.apiAppSettingsPut$Plain$Response(params, context);
    return resp.then((r: StrictHttpResponse<AppSettingsResponse>): AppSettingsResponse => r.body);
  }

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiAppSettingsPut$Json()` instead.
   *
   * This method sends `application/*+json` and handles request body of type `application/*+json`.
   */
  apiAppSettingsPut$Json$Response(params: ApiAppSettingsPut$Json$Params, context?: HttpContext): Promise<StrictHttpResponse<AppSettingsResponse>> {
    const obs = apiAppSettingsPut$Json(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiAppSettingsPut$Json$Response()` instead.
   *
   * This method sends `application/*+json` and handles request body of type `application/*+json`.
   */
  apiAppSettingsPut$Json(params: ApiAppSettingsPut$Json$Params, context?: HttpContext): Promise<AppSettingsResponse> {
    const resp = this.apiAppSettingsPut$Json$Response(params, context);
    return resp.then((r: StrictHttpResponse<AppSettingsResponse>): AppSettingsResponse => r.body);
  }

}
