/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { firstValueFrom } from 'rxjs';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { apiAuthActivatePost$Json } from '../fn/auth/api-auth-activate-post-json';
import { ApiAuthActivatePost$Json$Params } from '../fn/auth/api-auth-activate-post-json';
import { apiAuthActivatePost$Plain } from '../fn/auth/api-auth-activate-post-plain';
import { ApiAuthActivatePost$Plain$Params } from '../fn/auth/api-auth-activate-post-plain';
import { apiAuthLoginPost$Json } from '../fn/auth/api-auth-login-post-json';
import { ApiAuthLoginPost$Json$Params } from '../fn/auth/api-auth-login-post-json';
import { apiAuthLoginPost$Plain } from '../fn/auth/api-auth-login-post-plain';
import { ApiAuthLoginPost$Plain$Params } from '../fn/auth/api-auth-login-post-plain';
import { apiAuthRegisterPost$Json } from '../fn/auth/api-auth-register-post-json';
import { ApiAuthRegisterPost$Json$Params } from '../fn/auth/api-auth-register-post-json';
import { apiAuthRegisterPost$Plain } from '../fn/auth/api-auth-register-post-plain';
import { ApiAuthRegisterPost$Plain$Params } from '../fn/auth/api-auth-register-post-plain';
import { apiAuthResendActivationPost$Json } from '../fn/auth/api-auth-resend-activation-post-json';
import { ApiAuthResendActivationPost$Json$Params } from '../fn/auth/api-auth-resend-activation-post-json';
import { apiAuthResendActivationPost$Plain } from '../fn/auth/api-auth-resend-activation-post-plain';
import { ApiAuthResendActivationPost$Plain$Params } from '../fn/auth/api-auth-resend-activation-post-plain';
import { AuthResponse } from '../models/auth-response';
import { MessageResponse } from '../models/message-response';
import { RegisterResponse } from '../models/register-response';

@Injectable({ providedIn: 'root' })
export class AuthService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `apiAuthRegisterPost()` */
  static readonly ApiAuthRegisterPostPath = '/api/Auth/register';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiAuthRegisterPost$Plain()` instead.
   *
   * This method sends `application/*+json` and handles request body of type `application/*+json`.
   */
  apiAuthRegisterPost$Plain$Response(params: ApiAuthRegisterPost$Plain$Params, context?: HttpContext): Promise<StrictHttpResponse<RegisterResponse>> {
    const obs = apiAuthRegisterPost$Plain(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiAuthRegisterPost$Plain$Response()` instead.
   *
   * This method sends `application/*+json` and handles request body of type `application/*+json`.
   */
  apiAuthRegisterPost$Plain(params: ApiAuthRegisterPost$Plain$Params, context?: HttpContext): Promise<RegisterResponse> {
    const resp = this.apiAuthRegisterPost$Plain$Response(params, context);
    return resp.then((r: StrictHttpResponse<RegisterResponse>): RegisterResponse => r.body);
  }

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiAuthRegisterPost$Json()` instead.
   *
   * This method sends `application/*+json` and handles request body of type `application/*+json`.
   */
  apiAuthRegisterPost$Json$Response(params: ApiAuthRegisterPost$Json$Params, context?: HttpContext): Promise<StrictHttpResponse<RegisterResponse>> {
    const obs = apiAuthRegisterPost$Json(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiAuthRegisterPost$Json$Response()` instead.
   *
   * This method sends `application/*+json` and handles request body of type `application/*+json`.
   */
  apiAuthRegisterPost$Json(params: ApiAuthRegisterPost$Json$Params, context?: HttpContext): Promise<RegisterResponse> {
    const resp = this.apiAuthRegisterPost$Json$Response(params, context);
    return resp.then((r: StrictHttpResponse<RegisterResponse>): RegisterResponse => r.body);
  }

  /** Path part for operation `apiAuthActivatePost()` */
  static readonly ApiAuthActivatePostPath = '/api/Auth/activate';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiAuthActivatePost$Plain()` instead.
   *
   * This method sends `application/*+json` and handles request body of type `application/*+json`.
   */
  apiAuthActivatePost$Plain$Response(params: ApiAuthActivatePost$Plain$Params, context?: HttpContext): Promise<StrictHttpResponse<AuthResponse>> {
    const obs = apiAuthActivatePost$Plain(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiAuthActivatePost$Plain$Response()` instead.
   *
   * This method sends `application/*+json` and handles request body of type `application/*+json`.
   */
  apiAuthActivatePost$Plain(params: ApiAuthActivatePost$Plain$Params, context?: HttpContext): Promise<AuthResponse> {
    const resp = this.apiAuthActivatePost$Plain$Response(params, context);
    return resp.then((r: StrictHttpResponse<AuthResponse>): AuthResponse => r.body);
  }

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiAuthActivatePost$Json()` instead.
   *
   * This method sends `application/*+json` and handles request body of type `application/*+json`.
   */
  apiAuthActivatePost$Json$Response(params: ApiAuthActivatePost$Json$Params, context?: HttpContext): Promise<StrictHttpResponse<AuthResponse>> {
    const obs = apiAuthActivatePost$Json(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiAuthActivatePost$Json$Response()` instead.
   *
   * This method sends `application/*+json` and handles request body of type `application/*+json`.
   */
  apiAuthActivatePost$Json(params: ApiAuthActivatePost$Json$Params, context?: HttpContext): Promise<AuthResponse> {
    const resp = this.apiAuthActivatePost$Json$Response(params, context);
    return resp.then((r: StrictHttpResponse<AuthResponse>): AuthResponse => r.body);
  }

  /** Path part for operation `apiAuthResendActivationPost()` */
  static readonly ApiAuthResendActivationPostPath = '/api/Auth/resend-activation';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiAuthResendActivationPost$Plain()` instead.
   *
   * This method sends `application/*+json` and handles request body of type `application/*+json`.
   */
  apiAuthResendActivationPost$Plain$Response(params: ApiAuthResendActivationPost$Plain$Params, context?: HttpContext): Promise<StrictHttpResponse<MessageResponse>> {
    const obs = apiAuthResendActivationPost$Plain(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiAuthResendActivationPost$Plain$Response()` instead.
   *
   * This method sends `application/*+json` and handles request body of type `application/*+json`.
   */
  apiAuthResendActivationPost$Plain(params: ApiAuthResendActivationPost$Plain$Params, context?: HttpContext): Promise<MessageResponse> {
    const resp = this.apiAuthResendActivationPost$Plain$Response(params, context);
    return resp.then((r: StrictHttpResponse<MessageResponse>): MessageResponse => r.body);
  }

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiAuthResendActivationPost$Json()` instead.
   *
   * This method sends `application/*+json` and handles request body of type `application/*+json`.
   */
  apiAuthResendActivationPost$Json$Response(params: ApiAuthResendActivationPost$Json$Params, context?: HttpContext): Promise<StrictHttpResponse<MessageResponse>> {
    const obs = apiAuthResendActivationPost$Json(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiAuthResendActivationPost$Json$Response()` instead.
   *
   * This method sends `application/*+json` and handles request body of type `application/*+json`.
   */
  apiAuthResendActivationPost$Json(params: ApiAuthResendActivationPost$Json$Params, context?: HttpContext): Promise<MessageResponse> {
    const resp = this.apiAuthResendActivationPost$Json$Response(params, context);
    return resp.then((r: StrictHttpResponse<MessageResponse>): MessageResponse => r.body);
  }

  /** Path part for operation `apiAuthLoginPost()` */
  static readonly ApiAuthLoginPostPath = '/api/Auth/login';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiAuthLoginPost$Plain()` instead.
   *
   * This method sends `application/*+json` and handles request body of type `application/*+json`.
   */
  apiAuthLoginPost$Plain$Response(params: ApiAuthLoginPost$Plain$Params, context?: HttpContext): Promise<StrictHttpResponse<AuthResponse>> {
    const obs = apiAuthLoginPost$Plain(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiAuthLoginPost$Plain$Response()` instead.
   *
   * This method sends `application/*+json` and handles request body of type `application/*+json`.
   */
  apiAuthLoginPost$Plain(params: ApiAuthLoginPost$Plain$Params, context?: HttpContext): Promise<AuthResponse> {
    const resp = this.apiAuthLoginPost$Plain$Response(params, context);
    return resp.then((r: StrictHttpResponse<AuthResponse>): AuthResponse => r.body);
  }

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiAuthLoginPost$Json()` instead.
   *
   * This method sends `application/*+json` and handles request body of type `application/*+json`.
   */
  apiAuthLoginPost$Json$Response(params: ApiAuthLoginPost$Json$Params, context?: HttpContext): Promise<StrictHttpResponse<AuthResponse>> {
    const obs = apiAuthLoginPost$Json(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiAuthLoginPost$Json$Response()` instead.
   *
   * This method sends `application/*+json` and handles request body of type `application/*+json`.
   */
  apiAuthLoginPost$Json(params: ApiAuthLoginPost$Json$Params, context?: HttpContext): Promise<AuthResponse> {
    const resp = this.apiAuthLoginPost$Json$Response(params, context);
    return resp.then((r: StrictHttpResponse<AuthResponse>): AuthResponse => r.body);
  }

}
