/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { firstValueFrom } from 'rxjs';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { apiClientGet$Json } from '../fn/client/api-client-get-json';
import { ApiClientGet$Json$Params } from '../fn/client/api-client-get-json';
import { apiClientGet$Plain } from '../fn/client/api-client-get-plain';
import { ApiClientGet$Plain$Params } from '../fn/client/api-client-get-plain';
import { apiClientIdGet$Json } from '../fn/client/api-client-id-get-json';
import { ApiClientIdGet$Json$Params } from '../fn/client/api-client-id-get-json';
import { apiClientIdGet$Plain } from '../fn/client/api-client-id-get-plain';
import { ApiClientIdGet$Plain$Params } from '../fn/client/api-client-id-get-plain';
import { apiClientPost$Json } from '../fn/client/api-client-post-json';
import { ApiClientPost$Json$Params } from '../fn/client/api-client-post-json';
import { apiClientPost$Plain } from '../fn/client/api-client-post-plain';
import { ApiClientPost$Plain$Params } from '../fn/client/api-client-post-plain';
import { Client } from '../models/client';

@Injectable({ providedIn: 'root' })
export class ClientService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `apiClientGet()` */
  static readonly ApiClientGetPath = '/api/Client';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiClientGet$Plain()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiClientGet$Plain$Response(params?: ApiClientGet$Plain$Params, context?: HttpContext): Promise<StrictHttpResponse<Array<Client>>> {
    const obs = apiClientGet$Plain(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiClientGet$Plain$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiClientGet$Plain(params?: ApiClientGet$Plain$Params, context?: HttpContext): Promise<Array<Client>> {
    const resp = this.apiClientGet$Plain$Response(params, context);
    return resp.then((r: StrictHttpResponse<Array<Client>>): Array<Client> => r.body);
  }

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiClientGet$Json()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiClientGet$Json$Response(params?: ApiClientGet$Json$Params, context?: HttpContext): Promise<StrictHttpResponse<Array<Client>>> {
    const obs = apiClientGet$Json(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiClientGet$Json$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiClientGet$Json(params?: ApiClientGet$Json$Params, context?: HttpContext): Promise<Array<Client>> {
    const resp = this.apiClientGet$Json$Response(params, context);
    return resp.then((r: StrictHttpResponse<Array<Client>>): Array<Client> => r.body);
  }

  /** Path part for operation `apiClientPost()` */
  static readonly ApiClientPostPath = '/api/Client';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiClientPost$Plain()` instead.
   *
   * This method sends `application/*+json` and handles request body of type `application/*+json`.
   */
  apiClientPost$Plain$Response(params: ApiClientPost$Plain$Params, context?: HttpContext): Promise<StrictHttpResponse<Client>> {
    const obs = apiClientPost$Plain(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiClientPost$Plain$Response()` instead.
   *
   * This method sends `application/*+json` and handles request body of type `application/*+json`.
   */
  apiClientPost$Plain(params: ApiClientPost$Plain$Params, context?: HttpContext): Promise<Client> {
    const resp = this.apiClientPost$Plain$Response(params, context);
    return resp.then((r: StrictHttpResponse<Client>): Client => r.body);
  }

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiClientPost$Json()` instead.
   *
   * This method sends `application/*+json` and handles request body of type `application/*+json`.
   */
  apiClientPost$Json$Response(params: ApiClientPost$Json$Params, context?: HttpContext): Promise<StrictHttpResponse<Client>> {
    const obs = apiClientPost$Json(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiClientPost$Json$Response()` instead.
   *
   * This method sends `application/*+json` and handles request body of type `application/*+json`.
   */
  apiClientPost$Json(params: ApiClientPost$Json$Params, context?: HttpContext): Promise<Client> {
    const resp = this.apiClientPost$Json$Response(params, context);
    return resp.then((r: StrictHttpResponse<Client>): Client => r.body);
  }

  /** Path part for operation `apiClientIdGet()` */
  static readonly ApiClientIdGetPath = '/api/Client/{id}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiClientIdGet$Plain()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiClientIdGet$Plain$Response(params: ApiClientIdGet$Plain$Params, context?: HttpContext): Promise<StrictHttpResponse<Client>> {
    const obs = apiClientIdGet$Plain(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiClientIdGet$Plain$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiClientIdGet$Plain(params: ApiClientIdGet$Plain$Params, context?: HttpContext): Promise<Client> {
    const resp = this.apiClientIdGet$Plain$Response(params, context);
    return resp.then((r: StrictHttpResponse<Client>): Client => r.body);
  }

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiClientIdGet$Json()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiClientIdGet$Json$Response(params: ApiClientIdGet$Json$Params, context?: HttpContext): Promise<StrictHttpResponse<Client>> {
    const obs = apiClientIdGet$Json(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiClientIdGet$Json$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiClientIdGet$Json(params: ApiClientIdGet$Json$Params, context?: HttpContext): Promise<Client> {
    const resp = this.apiClientIdGet$Json$Response(params, context);
    return resp.then((r: StrictHttpResponse<Client>): Client => r.body);
  }

}
