/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { firstValueFrom } from 'rxjs';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { apiLeaveRequestGet$Json } from '../fn/leave-request/api-leave-request-get-json';
import { ApiLeaveRequestGet$Json$Params } from '../fn/leave-request/api-leave-request-get-json';
import { apiLeaveRequestGet$Plain } from '../fn/leave-request/api-leave-request-get-plain';
import { ApiLeaveRequestGet$Plain$Params } from '../fn/leave-request/api-leave-request-get-plain';
import { apiLeaveRequestIdGet$Json } from '../fn/leave-request/api-leave-request-id-get-json';
import { ApiLeaveRequestIdGet$Json$Params } from '../fn/leave-request/api-leave-request-id-get-json';
import { apiLeaveRequestIdGet$Plain } from '../fn/leave-request/api-leave-request-id-get-plain';
import { ApiLeaveRequestIdGet$Plain$Params } from '../fn/leave-request/api-leave-request-id-get-plain';
import { apiLeaveRequestPost$Json } from '../fn/leave-request/api-leave-request-post-json';
import { ApiLeaveRequestPost$Json$Params } from '../fn/leave-request/api-leave-request-post-json';
import { apiLeaveRequestPost$Plain } from '../fn/leave-request/api-leave-request-post-plain';
import { ApiLeaveRequestPost$Plain$Params } from '../fn/leave-request/api-leave-request-post-plain';
import { LeaveRequest } from '../models/leave-request';

@Injectable({ providedIn: 'root' })
export class LeaveRequestService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `apiLeaveRequestGet()` */
  static readonly ApiLeaveRequestGetPath = '/api/LeaveRequest';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiLeaveRequestGet$Plain()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiLeaveRequestGet$Plain$Response(params?: ApiLeaveRequestGet$Plain$Params, context?: HttpContext): Promise<StrictHttpResponse<Array<LeaveRequest>>> {
    const obs = apiLeaveRequestGet$Plain(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiLeaveRequestGet$Plain$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiLeaveRequestGet$Plain(params?: ApiLeaveRequestGet$Plain$Params, context?: HttpContext): Promise<Array<LeaveRequest>> {
    const resp = this.apiLeaveRequestGet$Plain$Response(params, context);
    return resp.then((r: StrictHttpResponse<Array<LeaveRequest>>): Array<LeaveRequest> => r.body);
  }

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiLeaveRequestGet$Json()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiLeaveRequestGet$Json$Response(params?: ApiLeaveRequestGet$Json$Params, context?: HttpContext): Promise<StrictHttpResponse<Array<LeaveRequest>>> {
    const obs = apiLeaveRequestGet$Json(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiLeaveRequestGet$Json$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiLeaveRequestGet$Json(params?: ApiLeaveRequestGet$Json$Params, context?: HttpContext): Promise<Array<LeaveRequest>> {
    const resp = this.apiLeaveRequestGet$Json$Response(params, context);
    return resp.then((r: StrictHttpResponse<Array<LeaveRequest>>): Array<LeaveRequest> => r.body);
  }

  /** Path part for operation `apiLeaveRequestPost()` */
  static readonly ApiLeaveRequestPostPath = '/api/LeaveRequest';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiLeaveRequestPost$Plain()` instead.
   *
   * This method sends `application/*+json` and handles request body of type `application/*+json`.
   */
  apiLeaveRequestPost$Plain$Response(params: ApiLeaveRequestPost$Plain$Params, context?: HttpContext): Promise<StrictHttpResponse<LeaveRequest>> {
    const obs = apiLeaveRequestPost$Plain(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiLeaveRequestPost$Plain$Response()` instead.
   *
   * This method sends `application/*+json` and handles request body of type `application/*+json`.
   */
  apiLeaveRequestPost$Plain(params: ApiLeaveRequestPost$Plain$Params, context?: HttpContext): Promise<LeaveRequest> {
    const resp = this.apiLeaveRequestPost$Plain$Response(params, context);
    return resp.then((r: StrictHttpResponse<LeaveRequest>): LeaveRequest => r.body);
  }

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiLeaveRequestPost$Json()` instead.
   *
   * This method sends `application/*+json` and handles request body of type `application/*+json`.
   */
  apiLeaveRequestPost$Json$Response(params: ApiLeaveRequestPost$Json$Params, context?: HttpContext): Promise<StrictHttpResponse<LeaveRequest>> {
    const obs = apiLeaveRequestPost$Json(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiLeaveRequestPost$Json$Response()` instead.
   *
   * This method sends `application/*+json` and handles request body of type `application/*+json`.
   */
  apiLeaveRequestPost$Json(params: ApiLeaveRequestPost$Json$Params, context?: HttpContext): Promise<LeaveRequest> {
    const resp = this.apiLeaveRequestPost$Json$Response(params, context);
    return resp.then((r: StrictHttpResponse<LeaveRequest>): LeaveRequest => r.body);
  }

  /** Path part for operation `apiLeaveRequestIdGet()` */
  static readonly ApiLeaveRequestIdGetPath = '/api/LeaveRequest/{id}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiLeaveRequestIdGet$Plain()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiLeaveRequestIdGet$Plain$Response(params: ApiLeaveRequestIdGet$Plain$Params, context?: HttpContext): Promise<StrictHttpResponse<LeaveRequest>> {
    const obs = apiLeaveRequestIdGet$Plain(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiLeaveRequestIdGet$Plain$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiLeaveRequestIdGet$Plain(params: ApiLeaveRequestIdGet$Plain$Params, context?: HttpContext): Promise<LeaveRequest> {
    const resp = this.apiLeaveRequestIdGet$Plain$Response(params, context);
    return resp.then((r: StrictHttpResponse<LeaveRequest>): LeaveRequest => r.body);
  }

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiLeaveRequestIdGet$Json()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiLeaveRequestIdGet$Json$Response(params: ApiLeaveRequestIdGet$Json$Params, context?: HttpContext): Promise<StrictHttpResponse<LeaveRequest>> {
    const obs = apiLeaveRequestIdGet$Json(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiLeaveRequestIdGet$Json$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiLeaveRequestIdGet$Json(params: ApiLeaveRequestIdGet$Json$Params, context?: HttpContext): Promise<LeaveRequest> {
    const resp = this.apiLeaveRequestIdGet$Json$Response(params, context);
    return resp.then((r: StrictHttpResponse<LeaveRequest>): LeaveRequest => r.body);
  }

}
