/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { firstValueFrom } from 'rxjs';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { apiLeaveBalanceGet$Json } from '../fn/leave-balance/api-leave-balance-get-json';
import { ApiLeaveBalanceGet$Json$Params } from '../fn/leave-balance/api-leave-balance-get-json';
import { apiLeaveBalanceGet$Plain } from '../fn/leave-balance/api-leave-balance-get-plain';
import { ApiLeaveBalanceGet$Plain$Params } from '../fn/leave-balance/api-leave-balance-get-plain';
import { apiLeaveBalanceIdGet$Json } from '../fn/leave-balance/api-leave-balance-id-get-json';
import { ApiLeaveBalanceIdGet$Json$Params } from '../fn/leave-balance/api-leave-balance-id-get-json';
import { apiLeaveBalanceIdGet$Plain } from '../fn/leave-balance/api-leave-balance-id-get-plain';
import { ApiLeaveBalanceIdGet$Plain$Params } from '../fn/leave-balance/api-leave-balance-id-get-plain';
import { apiLeaveBalancePost$Json } from '../fn/leave-balance/api-leave-balance-post-json';
import { ApiLeaveBalancePost$Json$Params } from '../fn/leave-balance/api-leave-balance-post-json';
import { apiLeaveBalancePost$Plain } from '../fn/leave-balance/api-leave-balance-post-plain';
import { ApiLeaveBalancePost$Plain$Params } from '../fn/leave-balance/api-leave-balance-post-plain';
import { LeaveBalance } from '../models/leave-balance';

@Injectable({ providedIn: 'root' })
export class LeaveBalanceService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `apiLeaveBalanceGet()` */
  static readonly ApiLeaveBalanceGetPath = '/api/LeaveBalance';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiLeaveBalanceGet$Plain()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiLeaveBalanceGet$Plain$Response(params?: ApiLeaveBalanceGet$Plain$Params, context?: HttpContext): Promise<StrictHttpResponse<Array<LeaveBalance>>> {
    const obs = apiLeaveBalanceGet$Plain(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiLeaveBalanceGet$Plain$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiLeaveBalanceGet$Plain(params?: ApiLeaveBalanceGet$Plain$Params, context?: HttpContext): Promise<Array<LeaveBalance>> {
    const resp = this.apiLeaveBalanceGet$Plain$Response(params, context);
    return resp.then((r: StrictHttpResponse<Array<LeaveBalance>>): Array<LeaveBalance> => r.body);
  }

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiLeaveBalanceGet$Json()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiLeaveBalanceGet$Json$Response(params?: ApiLeaveBalanceGet$Json$Params, context?: HttpContext): Promise<StrictHttpResponse<Array<LeaveBalance>>> {
    const obs = apiLeaveBalanceGet$Json(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiLeaveBalanceGet$Json$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiLeaveBalanceGet$Json(params?: ApiLeaveBalanceGet$Json$Params, context?: HttpContext): Promise<Array<LeaveBalance>> {
    const resp = this.apiLeaveBalanceGet$Json$Response(params, context);
    return resp.then((r: StrictHttpResponse<Array<LeaveBalance>>): Array<LeaveBalance> => r.body);
  }

  /** Path part for operation `apiLeaveBalancePost()` */
  static readonly ApiLeaveBalancePostPath = '/api/LeaveBalance';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiLeaveBalancePost$Plain()` instead.
   *
   * This method sends `application/*+json` and handles request body of type `application/*+json`.
   */
  apiLeaveBalancePost$Plain$Response(params: ApiLeaveBalancePost$Plain$Params, context?: HttpContext): Promise<StrictHttpResponse<LeaveBalance>> {
    const obs = apiLeaveBalancePost$Plain(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiLeaveBalancePost$Plain$Response()` instead.
   *
   * This method sends `application/*+json` and handles request body of type `application/*+json`.
   */
  apiLeaveBalancePost$Plain(params: ApiLeaveBalancePost$Plain$Params, context?: HttpContext): Promise<LeaveBalance> {
    const resp = this.apiLeaveBalancePost$Plain$Response(params, context);
    return resp.then((r: StrictHttpResponse<LeaveBalance>): LeaveBalance => r.body);
  }

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiLeaveBalancePost$Json()` instead.
   *
   * This method sends `application/*+json` and handles request body of type `application/*+json`.
   */
  apiLeaveBalancePost$Json$Response(params: ApiLeaveBalancePost$Json$Params, context?: HttpContext): Promise<StrictHttpResponse<LeaveBalance>> {
    const obs = apiLeaveBalancePost$Json(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiLeaveBalancePost$Json$Response()` instead.
   *
   * This method sends `application/*+json` and handles request body of type `application/*+json`.
   */
  apiLeaveBalancePost$Json(params: ApiLeaveBalancePost$Json$Params, context?: HttpContext): Promise<LeaveBalance> {
    const resp = this.apiLeaveBalancePost$Json$Response(params, context);
    return resp.then((r: StrictHttpResponse<LeaveBalance>): LeaveBalance => r.body);
  }

  /** Path part for operation `apiLeaveBalanceIdGet()` */
  static readonly ApiLeaveBalanceIdGetPath = '/api/LeaveBalance/{id}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiLeaveBalanceIdGet$Plain()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiLeaveBalanceIdGet$Plain$Response(params: ApiLeaveBalanceIdGet$Plain$Params, context?: HttpContext): Promise<StrictHttpResponse<LeaveBalance>> {
    const obs = apiLeaveBalanceIdGet$Plain(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiLeaveBalanceIdGet$Plain$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiLeaveBalanceIdGet$Plain(params: ApiLeaveBalanceIdGet$Plain$Params, context?: HttpContext): Promise<LeaveBalance> {
    const resp = this.apiLeaveBalanceIdGet$Plain$Response(params, context);
    return resp.then((r: StrictHttpResponse<LeaveBalance>): LeaveBalance => r.body);
  }

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiLeaveBalanceIdGet$Json()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiLeaveBalanceIdGet$Json$Response(params: ApiLeaveBalanceIdGet$Json$Params, context?: HttpContext): Promise<StrictHttpResponse<LeaveBalance>> {
    const obs = apiLeaveBalanceIdGet$Json(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiLeaveBalanceIdGet$Json$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiLeaveBalanceIdGet$Json(params: ApiLeaveBalanceIdGet$Json$Params, context?: HttpContext): Promise<LeaveBalance> {
    const resp = this.apiLeaveBalanceIdGet$Json$Response(params, context);
    return resp.then((r: StrictHttpResponse<LeaveBalance>): LeaveBalance => r.body);
  }

}
