/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { firstValueFrom } from 'rxjs';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { apiLeaveTypeGet$Json } from '../fn/leave-type/api-leave-type-get-json';
import { ApiLeaveTypeGet$Json$Params } from '../fn/leave-type/api-leave-type-get-json';
import { apiLeaveTypeGet$Plain } from '../fn/leave-type/api-leave-type-get-plain';
import { ApiLeaveTypeGet$Plain$Params } from '../fn/leave-type/api-leave-type-get-plain';
import { apiLeaveTypeIdGet$Json } from '../fn/leave-type/api-leave-type-id-get-json';
import { ApiLeaveTypeIdGet$Json$Params } from '../fn/leave-type/api-leave-type-id-get-json';
import { apiLeaveTypeIdGet$Plain } from '../fn/leave-type/api-leave-type-id-get-plain';
import { ApiLeaveTypeIdGet$Plain$Params } from '../fn/leave-type/api-leave-type-id-get-plain';
import { apiLeaveTypePost$Json } from '../fn/leave-type/api-leave-type-post-json';
import { ApiLeaveTypePost$Json$Params } from '../fn/leave-type/api-leave-type-post-json';
import { apiLeaveTypePost$Plain } from '../fn/leave-type/api-leave-type-post-plain';
import { ApiLeaveTypePost$Plain$Params } from '../fn/leave-type/api-leave-type-post-plain';
import { LeaveType } from '../models/leave-type';

@Injectable({ providedIn: 'root' })
export class LeaveTypeService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `apiLeaveTypeGet()` */
  static readonly ApiLeaveTypeGetPath = '/api/LeaveType';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiLeaveTypeGet$Plain()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiLeaveTypeGet$Plain$Response(params?: ApiLeaveTypeGet$Plain$Params, context?: HttpContext): Promise<StrictHttpResponse<Array<LeaveType>>> {
    const obs = apiLeaveTypeGet$Plain(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiLeaveTypeGet$Plain$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiLeaveTypeGet$Plain(params?: ApiLeaveTypeGet$Plain$Params, context?: HttpContext): Promise<Array<LeaveType>> {
    const resp = this.apiLeaveTypeGet$Plain$Response(params, context);
    return resp.then((r: StrictHttpResponse<Array<LeaveType>>): Array<LeaveType> => r.body);
  }

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiLeaveTypeGet$Json()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiLeaveTypeGet$Json$Response(params?: ApiLeaveTypeGet$Json$Params, context?: HttpContext): Promise<StrictHttpResponse<Array<LeaveType>>> {
    const obs = apiLeaveTypeGet$Json(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiLeaveTypeGet$Json$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiLeaveTypeGet$Json(params?: ApiLeaveTypeGet$Json$Params, context?: HttpContext): Promise<Array<LeaveType>> {
    const resp = this.apiLeaveTypeGet$Json$Response(params, context);
    return resp.then((r: StrictHttpResponse<Array<LeaveType>>): Array<LeaveType> => r.body);
  }

  /** Path part for operation `apiLeaveTypePost()` */
  static readonly ApiLeaveTypePostPath = '/api/LeaveType';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiLeaveTypePost$Plain()` instead.
   *
   * This method sends `application/*+json` and handles request body of type `application/*+json`.
   */
  apiLeaveTypePost$Plain$Response(params: ApiLeaveTypePost$Plain$Params, context?: HttpContext): Promise<StrictHttpResponse<LeaveType>> {
    const obs = apiLeaveTypePost$Plain(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiLeaveTypePost$Plain$Response()` instead.
   *
   * This method sends `application/*+json` and handles request body of type `application/*+json`.
   */
  apiLeaveTypePost$Plain(params: ApiLeaveTypePost$Plain$Params, context?: HttpContext): Promise<LeaveType> {
    const resp = this.apiLeaveTypePost$Plain$Response(params, context);
    return resp.then((r: StrictHttpResponse<LeaveType>): LeaveType => r.body);
  }

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiLeaveTypePost$Json()` instead.
   *
   * This method sends `application/*+json` and handles request body of type `application/*+json`.
   */
  apiLeaveTypePost$Json$Response(params: ApiLeaveTypePost$Json$Params, context?: HttpContext): Promise<StrictHttpResponse<LeaveType>> {
    const obs = apiLeaveTypePost$Json(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiLeaveTypePost$Json$Response()` instead.
   *
   * This method sends `application/*+json` and handles request body of type `application/*+json`.
   */
  apiLeaveTypePost$Json(params: ApiLeaveTypePost$Json$Params, context?: HttpContext): Promise<LeaveType> {
    const resp = this.apiLeaveTypePost$Json$Response(params, context);
    return resp.then((r: StrictHttpResponse<LeaveType>): LeaveType => r.body);
  }

  /** Path part for operation `apiLeaveTypeIdGet()` */
  static readonly ApiLeaveTypeIdGetPath = '/api/LeaveType/{id}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiLeaveTypeIdGet$Plain()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiLeaveTypeIdGet$Plain$Response(params: ApiLeaveTypeIdGet$Plain$Params, context?: HttpContext): Promise<StrictHttpResponse<LeaveType>> {
    const obs = apiLeaveTypeIdGet$Plain(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiLeaveTypeIdGet$Plain$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiLeaveTypeIdGet$Plain(params: ApiLeaveTypeIdGet$Plain$Params, context?: HttpContext): Promise<LeaveType> {
    const resp = this.apiLeaveTypeIdGet$Plain$Response(params, context);
    return resp.then((r: StrictHttpResponse<LeaveType>): LeaveType => r.body);
  }

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiLeaveTypeIdGet$Json()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiLeaveTypeIdGet$Json$Response(params: ApiLeaveTypeIdGet$Json$Params, context?: HttpContext): Promise<StrictHttpResponse<LeaveType>> {
    const obs = apiLeaveTypeIdGet$Json(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiLeaveTypeIdGet$Json$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiLeaveTypeIdGet$Json(params: ApiLeaveTypeIdGet$Json$Params, context?: HttpContext): Promise<LeaveType> {
    const resp = this.apiLeaveTypeIdGet$Json$Response(params, context);
    return resp.then((r: StrictHttpResponse<LeaveType>): LeaveType => r.body);
  }

}
