/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { firstValueFrom } from 'rxjs';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { apiProjectTaskGet$Json } from '../fn/project-task/api-project-task-get-json';
import { ApiProjectTaskGet$Json$Params } from '../fn/project-task/api-project-task-get-json';
import { apiProjectTaskGet$Plain } from '../fn/project-task/api-project-task-get-plain';
import { ApiProjectTaskGet$Plain$Params } from '../fn/project-task/api-project-task-get-plain';
import { apiProjectTaskIdGet$Json } from '../fn/project-task/api-project-task-id-get-json';
import { ApiProjectTaskIdGet$Json$Params } from '../fn/project-task/api-project-task-id-get-json';
import { apiProjectTaskIdGet$Plain } from '../fn/project-task/api-project-task-id-get-plain';
import { ApiProjectTaskIdGet$Plain$Params } from '../fn/project-task/api-project-task-id-get-plain';
import { apiProjectTaskPost$Json } from '../fn/project-task/api-project-task-post-json';
import { ApiProjectTaskPost$Json$Params } from '../fn/project-task/api-project-task-post-json';
import { apiProjectTaskPost$Plain } from '../fn/project-task/api-project-task-post-plain';
import { ApiProjectTaskPost$Plain$Params } from '../fn/project-task/api-project-task-post-plain';
import { ProjectTask } from '../models/project-task';

@Injectable({ providedIn: 'root' })
export class ProjectTaskService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `apiProjectTaskGet()` */
  static readonly ApiProjectTaskGetPath = '/api/ProjectTask';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiProjectTaskGet$Plain()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiProjectTaskGet$Plain$Response(params?: ApiProjectTaskGet$Plain$Params, context?: HttpContext): Promise<StrictHttpResponse<Array<ProjectTask>>> {
    const obs = apiProjectTaskGet$Plain(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiProjectTaskGet$Plain$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiProjectTaskGet$Plain(params?: ApiProjectTaskGet$Plain$Params, context?: HttpContext): Promise<Array<ProjectTask>> {
    const resp = this.apiProjectTaskGet$Plain$Response(params, context);
    return resp.then((r: StrictHttpResponse<Array<ProjectTask>>): Array<ProjectTask> => r.body);
  }

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiProjectTaskGet$Json()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiProjectTaskGet$Json$Response(params?: ApiProjectTaskGet$Json$Params, context?: HttpContext): Promise<StrictHttpResponse<Array<ProjectTask>>> {
    const obs = apiProjectTaskGet$Json(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiProjectTaskGet$Json$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiProjectTaskGet$Json(params?: ApiProjectTaskGet$Json$Params, context?: HttpContext): Promise<Array<ProjectTask>> {
    const resp = this.apiProjectTaskGet$Json$Response(params, context);
    return resp.then((r: StrictHttpResponse<Array<ProjectTask>>): Array<ProjectTask> => r.body);
  }

  /** Path part for operation `apiProjectTaskPost()` */
  static readonly ApiProjectTaskPostPath = '/api/ProjectTask';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiProjectTaskPost$Plain()` instead.
   *
   * This method sends `application/*+json` and handles request body of type `application/*+json`.
   */
  apiProjectTaskPost$Plain$Response(params: ApiProjectTaskPost$Plain$Params, context?: HttpContext): Promise<StrictHttpResponse<ProjectTask>> {
    const obs = apiProjectTaskPost$Plain(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiProjectTaskPost$Plain$Response()` instead.
   *
   * This method sends `application/*+json` and handles request body of type `application/*+json`.
   */
  apiProjectTaskPost$Plain(params: ApiProjectTaskPost$Plain$Params, context?: HttpContext): Promise<ProjectTask> {
    const resp = this.apiProjectTaskPost$Plain$Response(params, context);
    return resp.then((r: StrictHttpResponse<ProjectTask>): ProjectTask => r.body);
  }

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiProjectTaskPost$Json()` instead.
   *
   * This method sends `application/*+json` and handles request body of type `application/*+json`.
   */
  apiProjectTaskPost$Json$Response(params: ApiProjectTaskPost$Json$Params, context?: HttpContext): Promise<StrictHttpResponse<ProjectTask>> {
    const obs = apiProjectTaskPost$Json(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiProjectTaskPost$Json$Response()` instead.
   *
   * This method sends `application/*+json` and handles request body of type `application/*+json`.
   */
  apiProjectTaskPost$Json(params: ApiProjectTaskPost$Json$Params, context?: HttpContext): Promise<ProjectTask> {
    const resp = this.apiProjectTaskPost$Json$Response(params, context);
    return resp.then((r: StrictHttpResponse<ProjectTask>): ProjectTask => r.body);
  }

  /** Path part for operation `apiProjectTaskIdGet()` */
  static readonly ApiProjectTaskIdGetPath = '/api/ProjectTask/{id}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiProjectTaskIdGet$Plain()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiProjectTaskIdGet$Plain$Response(params: ApiProjectTaskIdGet$Plain$Params, context?: HttpContext): Promise<StrictHttpResponse<ProjectTask>> {
    const obs = apiProjectTaskIdGet$Plain(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiProjectTaskIdGet$Plain$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiProjectTaskIdGet$Plain(params: ApiProjectTaskIdGet$Plain$Params, context?: HttpContext): Promise<ProjectTask> {
    const resp = this.apiProjectTaskIdGet$Plain$Response(params, context);
    return resp.then((r: StrictHttpResponse<ProjectTask>): ProjectTask => r.body);
  }

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiProjectTaskIdGet$Json()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiProjectTaskIdGet$Json$Response(params: ApiProjectTaskIdGet$Json$Params, context?: HttpContext): Promise<StrictHttpResponse<ProjectTask>> {
    const obs = apiProjectTaskIdGet$Json(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiProjectTaskIdGet$Json$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiProjectTaskIdGet$Json(params: ApiProjectTaskIdGet$Json$Params, context?: HttpContext): Promise<ProjectTask> {
    const resp = this.apiProjectTaskIdGet$Json$Response(params, context);
    return resp.then((r: StrictHttpResponse<ProjectTask>): ProjectTask => r.body);
  }

}
