/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { firstValueFrom } from 'rxjs';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { apiPublicHolidayGet$Json } from '../fn/public-holiday/api-public-holiday-get-json';
import { ApiPublicHolidayGet$Json$Params } from '../fn/public-holiday/api-public-holiday-get-json';
import { apiPublicHolidayGet$Plain } from '../fn/public-holiday/api-public-holiday-get-plain';
import { ApiPublicHolidayGet$Plain$Params } from '../fn/public-holiday/api-public-holiday-get-plain';
import { apiPublicHolidayIdGet$Json } from '../fn/public-holiday/api-public-holiday-id-get-json';
import { ApiPublicHolidayIdGet$Json$Params } from '../fn/public-holiday/api-public-holiday-id-get-json';
import { apiPublicHolidayIdGet$Plain } from '../fn/public-holiday/api-public-holiday-id-get-plain';
import { ApiPublicHolidayIdGet$Plain$Params } from '../fn/public-holiday/api-public-holiday-id-get-plain';
import { apiPublicHolidayPost$Json } from '../fn/public-holiday/api-public-holiday-post-json';
import { ApiPublicHolidayPost$Json$Params } from '../fn/public-holiday/api-public-holiday-post-json';
import { apiPublicHolidayPost$Plain } from '../fn/public-holiday/api-public-holiday-post-plain';
import { ApiPublicHolidayPost$Plain$Params } from '../fn/public-holiday/api-public-holiday-post-plain';
import { PublicHoliday } from '../models/public-holiday';

@Injectable({ providedIn: 'root' })
export class PublicHolidayService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `apiPublicHolidayGet()` */
  static readonly ApiPublicHolidayGetPath = '/api/PublicHoliday';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiPublicHolidayGet$Plain()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiPublicHolidayGet$Plain$Response(params?: ApiPublicHolidayGet$Plain$Params, context?: HttpContext): Promise<StrictHttpResponse<Array<PublicHoliday>>> {
    const obs = apiPublicHolidayGet$Plain(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiPublicHolidayGet$Plain$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiPublicHolidayGet$Plain(params?: ApiPublicHolidayGet$Plain$Params, context?: HttpContext): Promise<Array<PublicHoliday>> {
    const resp = this.apiPublicHolidayGet$Plain$Response(params, context);
    return resp.then((r: StrictHttpResponse<Array<PublicHoliday>>): Array<PublicHoliday> => r.body);
  }

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiPublicHolidayGet$Json()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiPublicHolidayGet$Json$Response(params?: ApiPublicHolidayGet$Json$Params, context?: HttpContext): Promise<StrictHttpResponse<Array<PublicHoliday>>> {
    const obs = apiPublicHolidayGet$Json(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiPublicHolidayGet$Json$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiPublicHolidayGet$Json(params?: ApiPublicHolidayGet$Json$Params, context?: HttpContext): Promise<Array<PublicHoliday>> {
    const resp = this.apiPublicHolidayGet$Json$Response(params, context);
    return resp.then((r: StrictHttpResponse<Array<PublicHoliday>>): Array<PublicHoliday> => r.body);
  }

  /** Path part for operation `apiPublicHolidayPost()` */
  static readonly ApiPublicHolidayPostPath = '/api/PublicHoliday';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiPublicHolidayPost$Plain()` instead.
   *
   * This method sends `application/*+json` and handles request body of type `application/*+json`.
   */
  apiPublicHolidayPost$Plain$Response(params: ApiPublicHolidayPost$Plain$Params, context?: HttpContext): Promise<StrictHttpResponse<PublicHoliday>> {
    const obs = apiPublicHolidayPost$Plain(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiPublicHolidayPost$Plain$Response()` instead.
   *
   * This method sends `application/*+json` and handles request body of type `application/*+json`.
   */
  apiPublicHolidayPost$Plain(params: ApiPublicHolidayPost$Plain$Params, context?: HttpContext): Promise<PublicHoliday> {
    const resp = this.apiPublicHolidayPost$Plain$Response(params, context);
    return resp.then((r: StrictHttpResponse<PublicHoliday>): PublicHoliday => r.body);
  }

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiPublicHolidayPost$Json()` instead.
   *
   * This method sends `application/*+json` and handles request body of type `application/*+json`.
   */
  apiPublicHolidayPost$Json$Response(params: ApiPublicHolidayPost$Json$Params, context?: HttpContext): Promise<StrictHttpResponse<PublicHoliday>> {
    const obs = apiPublicHolidayPost$Json(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiPublicHolidayPost$Json$Response()` instead.
   *
   * This method sends `application/*+json` and handles request body of type `application/*+json`.
   */
  apiPublicHolidayPost$Json(params: ApiPublicHolidayPost$Json$Params, context?: HttpContext): Promise<PublicHoliday> {
    const resp = this.apiPublicHolidayPost$Json$Response(params, context);
    return resp.then((r: StrictHttpResponse<PublicHoliday>): PublicHoliday => r.body);
  }

  /** Path part for operation `apiPublicHolidayIdGet()` */
  static readonly ApiPublicHolidayIdGetPath = '/api/PublicHoliday/{id}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiPublicHolidayIdGet$Plain()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiPublicHolidayIdGet$Plain$Response(params: ApiPublicHolidayIdGet$Plain$Params, context?: HttpContext): Promise<StrictHttpResponse<PublicHoliday>> {
    const obs = apiPublicHolidayIdGet$Plain(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiPublicHolidayIdGet$Plain$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiPublicHolidayIdGet$Plain(params: ApiPublicHolidayIdGet$Plain$Params, context?: HttpContext): Promise<PublicHoliday> {
    const resp = this.apiPublicHolidayIdGet$Plain$Response(params, context);
    return resp.then((r: StrictHttpResponse<PublicHoliday>): PublicHoliday => r.body);
  }

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiPublicHolidayIdGet$Json()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiPublicHolidayIdGet$Json$Response(params: ApiPublicHolidayIdGet$Json$Params, context?: HttpContext): Promise<StrictHttpResponse<PublicHoliday>> {
    const obs = apiPublicHolidayIdGet$Json(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiPublicHolidayIdGet$Json$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiPublicHolidayIdGet$Json(params: ApiPublicHolidayIdGet$Json$Params, context?: HttpContext): Promise<PublicHoliday> {
    const resp = this.apiPublicHolidayIdGet$Json$Response(params, context);
    return resp.then((r: StrictHttpResponse<PublicHoliday>): PublicHoliday => r.body);
  }

}
