/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { firstValueFrom } from 'rxjs';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { apiRoleByNameRoleNameGet$Json } from '../fn/role/api-role-by-name-role-name-get-json';
import { ApiRoleByNameRoleNameGet$Json$Params } from '../fn/role/api-role-by-name-role-name-get-json';
import { apiRoleByNameRoleNameGet$Plain } from '../fn/role/api-role-by-name-role-name-get-plain';
import { ApiRoleByNameRoleNameGet$Plain$Params } from '../fn/role/api-role-by-name-role-name-get-plain';
import { apiRoleGet$Json } from '../fn/role/api-role-get-json';
import { ApiRoleGet$Json$Params } from '../fn/role/api-role-get-json';
import { apiRoleGet$Plain } from '../fn/role/api-role-get-plain';
import { ApiRoleGet$Plain$Params } from '../fn/role/api-role-get-plain';
import { apiRoleIdGet$Json } from '../fn/role/api-role-id-get-json';
import { ApiRoleIdGet$Json$Params } from '../fn/role/api-role-id-get-json';
import { apiRoleIdGet$Plain } from '../fn/role/api-role-id-get-plain';
import { ApiRoleIdGet$Plain$Params } from '../fn/role/api-role-id-get-plain';
import { apiRoleIdPermissionsGet$Json } from '../fn/role/api-role-id-permissions-get-json';
import { ApiRoleIdPermissionsGet$Json$Params } from '../fn/role/api-role-id-permissions-get-json';
import { apiRoleIdPermissionsGet$Plain } from '../fn/role/api-role-id-permissions-get-plain';
import { ApiRoleIdPermissionsGet$Plain$Params } from '../fn/role/api-role-id-permissions-get-plain';
import { apiRoleIdPermissionsPut$Json } from '../fn/role/api-role-id-permissions-put-json';
import { ApiRoleIdPermissionsPut$Json$Params } from '../fn/role/api-role-id-permissions-put-json';
import { apiRoleIdPermissionsPut$Plain } from '../fn/role/api-role-id-permissions-put-plain';
import { ApiRoleIdPermissionsPut$Plain$Params } from '../fn/role/api-role-id-permissions-put-plain';
import { apiRoleIdPut$Json } from '../fn/role/api-role-id-put-json';
import { ApiRoleIdPut$Json$Params } from '../fn/role/api-role-id-put-json';
import { apiRoleIdPut$Plain } from '../fn/role/api-role-id-put-plain';
import { ApiRoleIdPut$Plain$Params } from '../fn/role/api-role-id-put-plain';
import { apiRolePost$Json } from '../fn/role/api-role-post-json';
import { ApiRolePost$Json$Params } from '../fn/role/api-role-post-json';
import { apiRolePost$Plain } from '../fn/role/api-role-post-plain';
import { ApiRolePost$Plain$Params } from '../fn/role/api-role-post-plain';
import { Role } from '../models/role';
import { RolePermissionDto } from '../models/role-permission-dto';

@Injectable({ providedIn: 'root' })
export class RoleService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `apiRoleGet()` */
  static readonly ApiRoleGetPath = '/api/Role';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiRoleGet$Plain()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiRoleGet$Plain$Response(params?: ApiRoleGet$Plain$Params, context?: HttpContext): Promise<StrictHttpResponse<Array<Role>>> {
    const obs = apiRoleGet$Plain(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiRoleGet$Plain$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiRoleGet$Plain(params?: ApiRoleGet$Plain$Params, context?: HttpContext): Promise<Array<Role>> {
    const resp = this.apiRoleGet$Plain$Response(params, context);
    return resp.then((r: StrictHttpResponse<Array<Role>>): Array<Role> => r.body);
  }

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiRoleGet$Json()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiRoleGet$Json$Response(params?: ApiRoleGet$Json$Params, context?: HttpContext): Promise<StrictHttpResponse<Array<Role>>> {
    const obs = apiRoleGet$Json(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiRoleGet$Json$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiRoleGet$Json(params?: ApiRoleGet$Json$Params, context?: HttpContext): Promise<Array<Role>> {
    const resp = this.apiRoleGet$Json$Response(params, context);
    return resp.then((r: StrictHttpResponse<Array<Role>>): Array<Role> => r.body);
  }

  /** Path part for operation `apiRolePost()` */
  static readonly ApiRolePostPath = '/api/Role';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiRolePost$Plain()` instead.
   *
   * This method sends `application/*+json` and handles request body of type `application/*+json`.
   */
  apiRolePost$Plain$Response(params: ApiRolePost$Plain$Params, context?: HttpContext): Promise<StrictHttpResponse<Role>> {
    const obs = apiRolePost$Plain(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiRolePost$Plain$Response()` instead.
   *
   * This method sends `application/*+json` and handles request body of type `application/*+json`.
   */
  apiRolePost$Plain(params: ApiRolePost$Plain$Params, context?: HttpContext): Promise<Role> {
    const resp = this.apiRolePost$Plain$Response(params, context);
    return resp.then((r: StrictHttpResponse<Role>): Role => r.body);
  }

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiRolePost$Json()` instead.
   *
   * This method sends `application/*+json` and handles request body of type `application/*+json`.
   */
  apiRolePost$Json$Response(params: ApiRolePost$Json$Params, context?: HttpContext): Promise<StrictHttpResponse<Role>> {
    const obs = apiRolePost$Json(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiRolePost$Json$Response()` instead.
   *
   * This method sends `application/*+json` and handles request body of type `application/*+json`.
   */
  apiRolePost$Json(params: ApiRolePost$Json$Params, context?: HttpContext): Promise<Role> {
    const resp = this.apiRolePost$Json$Response(params, context);
    return resp.then((r: StrictHttpResponse<Role>): Role => r.body);
  }

  /** Path part for operation `apiRoleIdGet()` */
  static readonly ApiRoleIdGetPath = '/api/Role/{id}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiRoleIdGet$Plain()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiRoleIdGet$Plain$Response(params: ApiRoleIdGet$Plain$Params, context?: HttpContext): Promise<StrictHttpResponse<Role>> {
    const obs = apiRoleIdGet$Plain(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiRoleIdGet$Plain$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiRoleIdGet$Plain(params: ApiRoleIdGet$Plain$Params, context?: HttpContext): Promise<Role> {
    const resp = this.apiRoleIdGet$Plain$Response(params, context);
    return resp.then((r: StrictHttpResponse<Role>): Role => r.body);
  }

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiRoleIdGet$Json()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiRoleIdGet$Json$Response(params: ApiRoleIdGet$Json$Params, context?: HttpContext): Promise<StrictHttpResponse<Role>> {
    const obs = apiRoleIdGet$Json(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiRoleIdGet$Json$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiRoleIdGet$Json(params: ApiRoleIdGet$Json$Params, context?: HttpContext): Promise<Role> {
    const resp = this.apiRoleIdGet$Json$Response(params, context);
    return resp.then((r: StrictHttpResponse<Role>): Role => r.body);
  }

  /** Path part for operation `apiRoleIdPut()` */
  static readonly ApiRoleIdPutPath = '/api/Role/{id}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiRoleIdPut$Plain()` instead.
   *
   * This method sends `application/*+json` and handles request body of type `application/*+json`.
   */
  apiRoleIdPut$Plain$Response(params: ApiRoleIdPut$Plain$Params, context?: HttpContext): Promise<StrictHttpResponse<Role>> {
    const obs = apiRoleIdPut$Plain(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiRoleIdPut$Plain$Response()` instead.
   *
   * This method sends `application/*+json` and handles request body of type `application/*+json`.
   */
  apiRoleIdPut$Plain(params: ApiRoleIdPut$Plain$Params, context?: HttpContext): Promise<Role> {
    const resp = this.apiRoleIdPut$Plain$Response(params, context);
    return resp.then((r: StrictHttpResponse<Role>): Role => r.body);
  }

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiRoleIdPut$Json()` instead.
   *
   * This method sends `application/*+json` and handles request body of type `application/*+json`.
   */
  apiRoleIdPut$Json$Response(params: ApiRoleIdPut$Json$Params, context?: HttpContext): Promise<StrictHttpResponse<Role>> {
    const obs = apiRoleIdPut$Json(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiRoleIdPut$Json$Response()` instead.
   *
   * This method sends `application/*+json` and handles request body of type `application/*+json`.
   */
  apiRoleIdPut$Json(params: ApiRoleIdPut$Json$Params, context?: HttpContext): Promise<Role> {
    const resp = this.apiRoleIdPut$Json$Response(params, context);
    return resp.then((r: StrictHttpResponse<Role>): Role => r.body);
  }

  /** Path part for operation `apiRoleByNameRoleNameGet()` */
  static readonly ApiRoleByNameRoleNameGetPath = '/api/Role/by-name/{roleName}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiRoleByNameRoleNameGet$Plain()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiRoleByNameRoleNameGet$Plain$Response(params: ApiRoleByNameRoleNameGet$Plain$Params, context?: HttpContext): Promise<StrictHttpResponse<Role>> {
    const obs = apiRoleByNameRoleNameGet$Plain(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiRoleByNameRoleNameGet$Plain$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiRoleByNameRoleNameGet$Plain(params: ApiRoleByNameRoleNameGet$Plain$Params, context?: HttpContext): Promise<Role> {
    const resp = this.apiRoleByNameRoleNameGet$Plain$Response(params, context);
    return resp.then((r: StrictHttpResponse<Role>): Role => r.body);
  }

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiRoleByNameRoleNameGet$Json()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiRoleByNameRoleNameGet$Json$Response(params: ApiRoleByNameRoleNameGet$Json$Params, context?: HttpContext): Promise<StrictHttpResponse<Role>> {
    const obs = apiRoleByNameRoleNameGet$Json(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiRoleByNameRoleNameGet$Json$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiRoleByNameRoleNameGet$Json(params: ApiRoleByNameRoleNameGet$Json$Params, context?: HttpContext): Promise<Role> {
    const resp = this.apiRoleByNameRoleNameGet$Json$Response(params, context);
    return resp.then((r: StrictHttpResponse<Role>): Role => r.body);
  }

  /** Path part for operation `apiRoleIdPermissionsGet()` */
  static readonly ApiRoleIdPermissionsGetPath = '/api/Role/{id}/permissions';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiRoleIdPermissionsGet$Plain()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiRoleIdPermissionsGet$Plain$Response(params: ApiRoleIdPermissionsGet$Plain$Params, context?: HttpContext): Promise<StrictHttpResponse<Array<RolePermissionDto>>> {
    const obs = apiRoleIdPermissionsGet$Plain(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiRoleIdPermissionsGet$Plain$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiRoleIdPermissionsGet$Plain(params: ApiRoleIdPermissionsGet$Plain$Params, context?: HttpContext): Promise<Array<RolePermissionDto>> {
    const resp = this.apiRoleIdPermissionsGet$Plain$Response(params, context);
    return resp.then((r: StrictHttpResponse<Array<RolePermissionDto>>): Array<RolePermissionDto> => r.body);
  }

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiRoleIdPermissionsGet$Json()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiRoleIdPermissionsGet$Json$Response(params: ApiRoleIdPermissionsGet$Json$Params, context?: HttpContext): Promise<StrictHttpResponse<Array<RolePermissionDto>>> {
    const obs = apiRoleIdPermissionsGet$Json(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiRoleIdPermissionsGet$Json$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiRoleIdPermissionsGet$Json(params: ApiRoleIdPermissionsGet$Json$Params, context?: HttpContext): Promise<Array<RolePermissionDto>> {
    const resp = this.apiRoleIdPermissionsGet$Json$Response(params, context);
    return resp.then((r: StrictHttpResponse<Array<RolePermissionDto>>): Array<RolePermissionDto> => r.body);
  }

  /** Path part for operation `apiRoleIdPermissionsPut()` */
  static readonly ApiRoleIdPermissionsPutPath = '/api/Role/{id}/permissions';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiRoleIdPermissionsPut$Plain()` instead.
   *
   * This method sends `application/*+json` and handles request body of type `application/*+json`.
   */
  apiRoleIdPermissionsPut$Plain$Response(params: ApiRoleIdPermissionsPut$Plain$Params, context?: HttpContext): Promise<StrictHttpResponse<Array<RolePermissionDto>>> {
    const obs = apiRoleIdPermissionsPut$Plain(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiRoleIdPermissionsPut$Plain$Response()` instead.
   *
   * This method sends `application/*+json` and handles request body of type `application/*+json`.
   */
  apiRoleIdPermissionsPut$Plain(params: ApiRoleIdPermissionsPut$Plain$Params, context?: HttpContext): Promise<Array<RolePermissionDto>> {
    const resp = this.apiRoleIdPermissionsPut$Plain$Response(params, context);
    return resp.then((r: StrictHttpResponse<Array<RolePermissionDto>>): Array<RolePermissionDto> => r.body);
  }

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiRoleIdPermissionsPut$Json()` instead.
   *
   * This method sends `application/*+json` and handles request body of type `application/*+json`.
   */
  apiRoleIdPermissionsPut$Json$Response(params: ApiRoleIdPermissionsPut$Json$Params, context?: HttpContext): Promise<StrictHttpResponse<Array<RolePermissionDto>>> {
    const obs = apiRoleIdPermissionsPut$Json(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiRoleIdPermissionsPut$Json$Response()` instead.
   *
   * This method sends `application/*+json` and handles request body of type `application/*+json`.
   */
  apiRoleIdPermissionsPut$Json(params: ApiRoleIdPermissionsPut$Json$Params, context?: HttpContext): Promise<Array<RolePermissionDto>> {
    const resp = this.apiRoleIdPermissionsPut$Json$Response(params, context);
    return resp.then((r: StrictHttpResponse<Array<RolePermissionDto>>): Array<RolePermissionDto> => r.body);
  }

}
