/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { firstValueFrom } from 'rxjs';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { apiRuleGet$Json } from '../fn/rule/api-rule-get-json';
import { ApiRuleGet$Json$Params } from '../fn/rule/api-rule-get-json';
import { apiRuleGet$Plain } from '../fn/rule/api-rule-get-plain';
import { ApiRuleGet$Plain$Params } from '../fn/rule/api-rule-get-plain';
import { apiRuleIdGet$Json } from '../fn/rule/api-rule-id-get-json';
import { ApiRuleIdGet$Json$Params } from '../fn/rule/api-rule-id-get-json';
import { apiRuleIdGet$Plain } from '../fn/rule/api-rule-id-get-plain';
import { ApiRuleIdGet$Plain$Params } from '../fn/rule/api-rule-id-get-plain';
import { apiRulePost$Json } from '../fn/rule/api-rule-post-json';
import { ApiRulePost$Json$Params } from '../fn/rule/api-rule-post-json';
import { apiRulePost$Plain } from '../fn/rule/api-rule-post-plain';
import { ApiRulePost$Plain$Params } from '../fn/rule/api-rule-post-plain';
import { Rule } from '../models/rule';

@Injectable({ providedIn: 'root' })
export class RuleService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `apiRuleGet()` */
  static readonly ApiRuleGetPath = '/api/Rule';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiRuleGet$Plain()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiRuleGet$Plain$Response(params?: ApiRuleGet$Plain$Params, context?: HttpContext): Promise<StrictHttpResponse<Array<Rule>>> {
    const obs = apiRuleGet$Plain(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiRuleGet$Plain$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiRuleGet$Plain(params?: ApiRuleGet$Plain$Params, context?: HttpContext): Promise<Array<Rule>> {
    const resp = this.apiRuleGet$Plain$Response(params, context);
    return resp.then((r: StrictHttpResponse<Array<Rule>>): Array<Rule> => r.body);
  }

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiRuleGet$Json()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiRuleGet$Json$Response(params?: ApiRuleGet$Json$Params, context?: HttpContext): Promise<StrictHttpResponse<Array<Rule>>> {
    const obs = apiRuleGet$Json(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiRuleGet$Json$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiRuleGet$Json(params?: ApiRuleGet$Json$Params, context?: HttpContext): Promise<Array<Rule>> {
    const resp = this.apiRuleGet$Json$Response(params, context);
    return resp.then((r: StrictHttpResponse<Array<Rule>>): Array<Rule> => r.body);
  }

  /** Path part for operation `apiRulePost()` */
  static readonly ApiRulePostPath = '/api/Rule';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiRulePost$Plain()` instead.
   *
   * This method sends `application/*+json` and handles request body of type `application/*+json`.
   */
  apiRulePost$Plain$Response(params: ApiRulePost$Plain$Params, context?: HttpContext): Promise<StrictHttpResponse<Rule>> {
    const obs = apiRulePost$Plain(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiRulePost$Plain$Response()` instead.
   *
   * This method sends `application/*+json` and handles request body of type `application/*+json`.
   */
  apiRulePost$Plain(params: ApiRulePost$Plain$Params, context?: HttpContext): Promise<Rule> {
    const resp = this.apiRulePost$Plain$Response(params, context);
    return resp.then((r: StrictHttpResponse<Rule>): Rule => r.body);
  }

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiRulePost$Json()` instead.
   *
   * This method sends `application/*+json` and handles request body of type `application/*+json`.
   */
  apiRulePost$Json$Response(params: ApiRulePost$Json$Params, context?: HttpContext): Promise<StrictHttpResponse<Rule>> {
    const obs = apiRulePost$Json(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiRulePost$Json$Response()` instead.
   *
   * This method sends `application/*+json` and handles request body of type `application/*+json`.
   */
  apiRulePost$Json(params: ApiRulePost$Json$Params, context?: HttpContext): Promise<Rule> {
    const resp = this.apiRulePost$Json$Response(params, context);
    return resp.then((r: StrictHttpResponse<Rule>): Rule => r.body);
  }

  /** Path part for operation `apiRuleIdGet()` */
  static readonly ApiRuleIdGetPath = '/api/Rule/{id}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiRuleIdGet$Plain()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiRuleIdGet$Plain$Response(params: ApiRuleIdGet$Plain$Params, context?: HttpContext): Promise<StrictHttpResponse<Rule>> {
    const obs = apiRuleIdGet$Plain(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiRuleIdGet$Plain$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiRuleIdGet$Plain(params: ApiRuleIdGet$Plain$Params, context?: HttpContext): Promise<Rule> {
    const resp = this.apiRuleIdGet$Plain$Response(params, context);
    return resp.then((r: StrictHttpResponse<Rule>): Rule => r.body);
  }

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiRuleIdGet$Json()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiRuleIdGet$Json$Response(params: ApiRuleIdGet$Json$Params, context?: HttpContext): Promise<StrictHttpResponse<Rule>> {
    const obs = apiRuleIdGet$Json(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiRuleIdGet$Json$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiRuleIdGet$Json(params: ApiRuleIdGet$Json$Params, context?: HttpContext): Promise<Rule> {
    const resp = this.apiRuleIdGet$Json$Response(params, context);
    return resp.then((r: StrictHttpResponse<Rule>): Rule => r.body);
  }

}
