/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { firstValueFrom } from 'rxjs';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { apiSmtpSettingsGet$Json } from '../fn/smtp-settings/api-smtp-settings-get-json';
import { ApiSmtpSettingsGet$Json$Params } from '../fn/smtp-settings/api-smtp-settings-get-json';
import { apiSmtpSettingsGet$Plain } from '../fn/smtp-settings/api-smtp-settings-get-plain';
import { ApiSmtpSettingsGet$Plain$Params } from '../fn/smtp-settings/api-smtp-settings-get-plain';
import { apiSmtpSettingsPut$Json } from '../fn/smtp-settings/api-smtp-settings-put-json';
import { ApiSmtpSettingsPut$Json$Params } from '../fn/smtp-settings/api-smtp-settings-put-json';
import { apiSmtpSettingsPut$Plain } from '../fn/smtp-settings/api-smtp-settings-put-plain';
import { ApiSmtpSettingsPut$Plain$Params } from '../fn/smtp-settings/api-smtp-settings-put-plain';
import { SmtpSettingsResponse } from '../models/smtp-settings-response';

@Injectable({ providedIn: 'root' })
export class SmtpSettingsService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `apiSmtpSettingsGet()` */
  static readonly ApiSmtpSettingsGetPath = '/api/SmtpSettings';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiSmtpSettingsGet$Plain()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiSmtpSettingsGet$Plain$Response(params?: ApiSmtpSettingsGet$Plain$Params, context?: HttpContext): Promise<StrictHttpResponse<SmtpSettingsResponse>> {
    const obs = apiSmtpSettingsGet$Plain(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiSmtpSettingsGet$Plain$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiSmtpSettingsGet$Plain(params?: ApiSmtpSettingsGet$Plain$Params, context?: HttpContext): Promise<SmtpSettingsResponse> {
    const resp = this.apiSmtpSettingsGet$Plain$Response(params, context);
    return resp.then((r: StrictHttpResponse<SmtpSettingsResponse>): SmtpSettingsResponse => r.body);
  }

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiSmtpSettingsGet$Json()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiSmtpSettingsGet$Json$Response(params?: ApiSmtpSettingsGet$Json$Params, context?: HttpContext): Promise<StrictHttpResponse<SmtpSettingsResponse>> {
    const obs = apiSmtpSettingsGet$Json(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiSmtpSettingsGet$Json$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiSmtpSettingsGet$Json(params?: ApiSmtpSettingsGet$Json$Params, context?: HttpContext): Promise<SmtpSettingsResponse> {
    const resp = this.apiSmtpSettingsGet$Json$Response(params, context);
    return resp.then((r: StrictHttpResponse<SmtpSettingsResponse>): SmtpSettingsResponse => r.body);
  }

  /** Path part for operation `apiSmtpSettingsPut()` */
  static readonly ApiSmtpSettingsPutPath = '/api/SmtpSettings';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiSmtpSettingsPut$Plain()` instead.
   *
   * This method sends `application/*+json` and handles request body of type `application/*+json`.
   */
  apiSmtpSettingsPut$Plain$Response(params: ApiSmtpSettingsPut$Plain$Params, context?: HttpContext): Promise<StrictHttpResponse<SmtpSettingsResponse>> {
    const obs = apiSmtpSettingsPut$Plain(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiSmtpSettingsPut$Plain$Response()` instead.
   *
   * This method sends `application/*+json` and handles request body of type `application/*+json`.
   */
  apiSmtpSettingsPut$Plain(params: ApiSmtpSettingsPut$Plain$Params, context?: HttpContext): Promise<SmtpSettingsResponse> {
    const resp = this.apiSmtpSettingsPut$Plain$Response(params, context);
    return resp.then((r: StrictHttpResponse<SmtpSettingsResponse>): SmtpSettingsResponse => r.body);
  }

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiSmtpSettingsPut$Json()` instead.
   *
   * This method sends `application/*+json` and handles request body of type `application/*+json`.
   */
  apiSmtpSettingsPut$Json$Response(params: ApiSmtpSettingsPut$Json$Params, context?: HttpContext): Promise<StrictHttpResponse<SmtpSettingsResponse>> {
    const obs = apiSmtpSettingsPut$Json(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiSmtpSettingsPut$Json$Response()` instead.
   *
   * This method sends `application/*+json` and handles request body of type `application/*+json`.
   */
  apiSmtpSettingsPut$Json(params: ApiSmtpSettingsPut$Json$Params, context?: HttpContext): Promise<SmtpSettingsResponse> {
    const resp = this.apiSmtpSettingsPut$Json$Response(params, context);
    return resp.then((r: StrictHttpResponse<SmtpSettingsResponse>): SmtpSettingsResponse => r.body);
  }

}
