/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { firstValueFrom } from 'rxjs';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { apiTagGet$Json } from '../fn/tag/api-tag-get-json';
import { ApiTagGet$Json$Params } from '../fn/tag/api-tag-get-json';
import { apiTagGet$Plain } from '../fn/tag/api-tag-get-plain';
import { ApiTagGet$Plain$Params } from '../fn/tag/api-tag-get-plain';
import { apiTagIdGet$Json } from '../fn/tag/api-tag-id-get-json';
import { ApiTagIdGet$Json$Params } from '../fn/tag/api-tag-id-get-json';
import { apiTagIdGet$Plain } from '../fn/tag/api-tag-id-get-plain';
import { ApiTagIdGet$Plain$Params } from '../fn/tag/api-tag-id-get-plain';
import { apiTagPost$Json } from '../fn/tag/api-tag-post-json';
import { ApiTagPost$Json$Params } from '../fn/tag/api-tag-post-json';
import { apiTagPost$Plain } from '../fn/tag/api-tag-post-plain';
import { ApiTagPost$Plain$Params } from '../fn/tag/api-tag-post-plain';
import { Tag } from '../models/tag';

@Injectable({ providedIn: 'root' })
export class TagService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `apiTagGet()` */
  static readonly ApiTagGetPath = '/api/Tag';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiTagGet$Plain()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiTagGet$Plain$Response(params?: ApiTagGet$Plain$Params, context?: HttpContext): Promise<StrictHttpResponse<Array<Tag>>> {
    const obs = apiTagGet$Plain(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiTagGet$Plain$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiTagGet$Plain(params?: ApiTagGet$Plain$Params, context?: HttpContext): Promise<Array<Tag>> {
    const resp = this.apiTagGet$Plain$Response(params, context);
    return resp.then((r: StrictHttpResponse<Array<Tag>>): Array<Tag> => r.body);
  }

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiTagGet$Json()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiTagGet$Json$Response(params?: ApiTagGet$Json$Params, context?: HttpContext): Promise<StrictHttpResponse<Array<Tag>>> {
    const obs = apiTagGet$Json(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiTagGet$Json$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiTagGet$Json(params?: ApiTagGet$Json$Params, context?: HttpContext): Promise<Array<Tag>> {
    const resp = this.apiTagGet$Json$Response(params, context);
    return resp.then((r: StrictHttpResponse<Array<Tag>>): Array<Tag> => r.body);
  }

  /** Path part for operation `apiTagPost()` */
  static readonly ApiTagPostPath = '/api/Tag';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiTagPost$Plain()` instead.
   *
   * This method sends `application/*+json` and handles request body of type `application/*+json`.
   */
  apiTagPost$Plain$Response(params: ApiTagPost$Plain$Params, context?: HttpContext): Promise<StrictHttpResponse<Tag>> {
    const obs = apiTagPost$Plain(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiTagPost$Plain$Response()` instead.
   *
   * This method sends `application/*+json` and handles request body of type `application/*+json`.
   */
  apiTagPost$Plain(params: ApiTagPost$Plain$Params, context?: HttpContext): Promise<Tag> {
    const resp = this.apiTagPost$Plain$Response(params, context);
    return resp.then((r: StrictHttpResponse<Tag>): Tag => r.body);
  }

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiTagPost$Json()` instead.
   *
   * This method sends `application/*+json` and handles request body of type `application/*+json`.
   */
  apiTagPost$Json$Response(params: ApiTagPost$Json$Params, context?: HttpContext): Promise<StrictHttpResponse<Tag>> {
    const obs = apiTagPost$Json(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiTagPost$Json$Response()` instead.
   *
   * This method sends `application/*+json` and handles request body of type `application/*+json`.
   */
  apiTagPost$Json(params: ApiTagPost$Json$Params, context?: HttpContext): Promise<Tag> {
    const resp = this.apiTagPost$Json$Response(params, context);
    return resp.then((r: StrictHttpResponse<Tag>): Tag => r.body);
  }

  /** Path part for operation `apiTagIdGet()` */
  static readonly ApiTagIdGetPath = '/api/Tag/{id}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiTagIdGet$Plain()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiTagIdGet$Plain$Response(params: ApiTagIdGet$Plain$Params, context?: HttpContext): Promise<StrictHttpResponse<Tag>> {
    const obs = apiTagIdGet$Plain(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiTagIdGet$Plain$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiTagIdGet$Plain(params: ApiTagIdGet$Plain$Params, context?: HttpContext): Promise<Tag> {
    const resp = this.apiTagIdGet$Plain$Response(params, context);
    return resp.then((r: StrictHttpResponse<Tag>): Tag => r.body);
  }

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiTagIdGet$Json()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiTagIdGet$Json$Response(params: ApiTagIdGet$Json$Params, context?: HttpContext): Promise<StrictHttpResponse<Tag>> {
    const obs = apiTagIdGet$Json(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiTagIdGet$Json$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiTagIdGet$Json(params: ApiTagIdGet$Json$Params, context?: HttpContext): Promise<Tag> {
    const resp = this.apiTagIdGet$Json$Response(params, context);
    return resp.then((r: StrictHttpResponse<Tag>): Tag => r.body);
  }

}
