/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { firstValueFrom } from 'rxjs';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { apiTeamByNameTeamNameGet$Json } from '../fn/team/api-team-by-name-team-name-get-json';
import { ApiTeamByNameTeamNameGet$Json$Params } from '../fn/team/api-team-by-name-team-name-get-json';
import { apiTeamByNameTeamNameGet$Plain } from '../fn/team/api-team-by-name-team-name-get-plain';
import { ApiTeamByNameTeamNameGet$Plain$Params } from '../fn/team/api-team-by-name-team-name-get-plain';
import { apiTeamGet$Json } from '../fn/team/api-team-get-json';
import { ApiTeamGet$Json$Params } from '../fn/team/api-team-get-json';
import { apiTeamGet$Plain } from '../fn/team/api-team-get-plain';
import { ApiTeamGet$Plain$Params } from '../fn/team/api-team-get-plain';
import { apiTeamIdGet$Json } from '../fn/team/api-team-id-get-json';
import { ApiTeamIdGet$Json$Params } from '../fn/team/api-team-id-get-json';
import { apiTeamIdGet$Plain } from '../fn/team/api-team-id-get-plain';
import { ApiTeamIdGet$Plain$Params } from '../fn/team/api-team-id-get-plain';
import { apiTeamIdPut$Json } from '../fn/team/api-team-id-put-json';
import { ApiTeamIdPut$Json$Params } from '../fn/team/api-team-id-put-json';
import { apiTeamIdPut$Plain } from '../fn/team/api-team-id-put-plain';
import { ApiTeamIdPut$Plain$Params } from '../fn/team/api-team-id-put-plain';
import { apiTeamPost$Json } from '../fn/team/api-team-post-json';
import { ApiTeamPost$Json$Params } from '../fn/team/api-team-post-json';
import { apiTeamPost$Plain } from '../fn/team/api-team-post-plain';
import { ApiTeamPost$Plain$Params } from '../fn/team/api-team-post-plain';
import { Team } from '../models/team';

@Injectable({ providedIn: 'root' })
export class TeamService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `apiTeamGet()` */
  static readonly ApiTeamGetPath = '/api/Team';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiTeamGet$Plain()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiTeamGet$Plain$Response(params?: ApiTeamGet$Plain$Params, context?: HttpContext): Promise<StrictHttpResponse<Array<Team>>> {
    const obs = apiTeamGet$Plain(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiTeamGet$Plain$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiTeamGet$Plain(params?: ApiTeamGet$Plain$Params, context?: HttpContext): Promise<Array<Team>> {
    const resp = this.apiTeamGet$Plain$Response(params, context);
    return resp.then((r: StrictHttpResponse<Array<Team>>): Array<Team> => r.body);
  }

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiTeamGet$Json()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiTeamGet$Json$Response(params?: ApiTeamGet$Json$Params, context?: HttpContext): Promise<StrictHttpResponse<Array<Team>>> {
    const obs = apiTeamGet$Json(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiTeamGet$Json$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiTeamGet$Json(params?: ApiTeamGet$Json$Params, context?: HttpContext): Promise<Array<Team>> {
    const resp = this.apiTeamGet$Json$Response(params, context);
    return resp.then((r: StrictHttpResponse<Array<Team>>): Array<Team> => r.body);
  }

  /** Path part for operation `apiTeamPost()` */
  static readonly ApiTeamPostPath = '/api/Team';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiTeamPost$Plain()` instead.
   *
   * This method sends `application/*+json` and handles request body of type `application/*+json`.
   */
  apiTeamPost$Plain$Response(params: ApiTeamPost$Plain$Params, context?: HttpContext): Promise<StrictHttpResponse<Team>> {
    const obs = apiTeamPost$Plain(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiTeamPost$Plain$Response()` instead.
   *
   * This method sends `application/*+json` and handles request body of type `application/*+json`.
   */
  apiTeamPost$Plain(params: ApiTeamPost$Plain$Params, context?: HttpContext): Promise<Team> {
    const resp = this.apiTeamPost$Plain$Response(params, context);
    return resp.then((r: StrictHttpResponse<Team>): Team => r.body);
  }

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiTeamPost$Json()` instead.
   *
   * This method sends `application/*+json` and handles request body of type `application/*+json`.
   */
  apiTeamPost$Json$Response(params: ApiTeamPost$Json$Params, context?: HttpContext): Promise<StrictHttpResponse<Team>> {
    const obs = apiTeamPost$Json(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiTeamPost$Json$Response()` instead.
   *
   * This method sends `application/*+json` and handles request body of type `application/*+json`.
   */
  apiTeamPost$Json(params: ApiTeamPost$Json$Params, context?: HttpContext): Promise<Team> {
    const resp = this.apiTeamPost$Json$Response(params, context);
    return resp.then((r: StrictHttpResponse<Team>): Team => r.body);
  }

  /** Path part for operation `apiTeamIdGet()` */
  static readonly ApiTeamIdGetPath = '/api/Team/{id}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiTeamIdGet$Plain()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiTeamIdGet$Plain$Response(params: ApiTeamIdGet$Plain$Params, context?: HttpContext): Promise<StrictHttpResponse<Team>> {
    const obs = apiTeamIdGet$Plain(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiTeamIdGet$Plain$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiTeamIdGet$Plain(params: ApiTeamIdGet$Plain$Params, context?: HttpContext): Promise<Team> {
    const resp = this.apiTeamIdGet$Plain$Response(params, context);
    return resp.then((r: StrictHttpResponse<Team>): Team => r.body);
  }

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiTeamIdGet$Json()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiTeamIdGet$Json$Response(params: ApiTeamIdGet$Json$Params, context?: HttpContext): Promise<StrictHttpResponse<Team>> {
    const obs = apiTeamIdGet$Json(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiTeamIdGet$Json$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiTeamIdGet$Json(params: ApiTeamIdGet$Json$Params, context?: HttpContext): Promise<Team> {
    const resp = this.apiTeamIdGet$Json$Response(params, context);
    return resp.then((r: StrictHttpResponse<Team>): Team => r.body);
  }

  /** Path part for operation `apiTeamIdPut()` */
  static readonly ApiTeamIdPutPath = '/api/Team/{id}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiTeamIdPut$Plain()` instead.
   *
   * This method sends `application/*+json` and handles request body of type `application/*+json`.
   */
  apiTeamIdPut$Plain$Response(params: ApiTeamIdPut$Plain$Params, context?: HttpContext): Promise<StrictHttpResponse<Team>> {
    const obs = apiTeamIdPut$Plain(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiTeamIdPut$Plain$Response()` instead.
   *
   * This method sends `application/*+json` and handles request body of type `application/*+json`.
   */
  apiTeamIdPut$Plain(params: ApiTeamIdPut$Plain$Params, context?: HttpContext): Promise<Team> {
    const resp = this.apiTeamIdPut$Plain$Response(params, context);
    return resp.then((r: StrictHttpResponse<Team>): Team => r.body);
  }

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiTeamIdPut$Json()` instead.
   *
   * This method sends `application/*+json` and handles request body of type `application/*+json`.
   */
  apiTeamIdPut$Json$Response(params: ApiTeamIdPut$Json$Params, context?: HttpContext): Promise<StrictHttpResponse<Team>> {
    const obs = apiTeamIdPut$Json(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiTeamIdPut$Json$Response()` instead.
   *
   * This method sends `application/*+json` and handles request body of type `application/*+json`.
   */
  apiTeamIdPut$Json(params: ApiTeamIdPut$Json$Params, context?: HttpContext): Promise<Team> {
    const resp = this.apiTeamIdPut$Json$Response(params, context);
    return resp.then((r: StrictHttpResponse<Team>): Team => r.body);
  }

  /** Path part for operation `apiTeamByNameTeamNameGet()` */
  static readonly ApiTeamByNameTeamNameGetPath = '/api/Team/by-name/{teamName}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiTeamByNameTeamNameGet$Plain()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiTeamByNameTeamNameGet$Plain$Response(params: ApiTeamByNameTeamNameGet$Plain$Params, context?: HttpContext): Promise<StrictHttpResponse<Team>> {
    const obs = apiTeamByNameTeamNameGet$Plain(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiTeamByNameTeamNameGet$Plain$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiTeamByNameTeamNameGet$Plain(params: ApiTeamByNameTeamNameGet$Plain$Params, context?: HttpContext): Promise<Team> {
    const resp = this.apiTeamByNameTeamNameGet$Plain$Response(params, context);
    return resp.then((r: StrictHttpResponse<Team>): Team => r.body);
  }

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiTeamByNameTeamNameGet$Json()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiTeamByNameTeamNameGet$Json$Response(params: ApiTeamByNameTeamNameGet$Json$Params, context?: HttpContext): Promise<StrictHttpResponse<Team>> {
    const obs = apiTeamByNameTeamNameGet$Json(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiTeamByNameTeamNameGet$Json$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiTeamByNameTeamNameGet$Json(params: ApiTeamByNameTeamNameGet$Json$Params, context?: HttpContext): Promise<Team> {
    const resp = this.apiTeamByNameTeamNameGet$Json$Response(params, context);
    return resp.then((r: StrictHttpResponse<Team>): Team => r.body);
  }

}
