/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { firstValueFrom } from 'rxjs';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { apiTimeEntryAuditLogGet$Json } from '../fn/time-entry-audit-log/api-time-entry-audit-log-get-json';
import { ApiTimeEntryAuditLogGet$Json$Params } from '../fn/time-entry-audit-log/api-time-entry-audit-log-get-json';
import { apiTimeEntryAuditLogGet$Plain } from '../fn/time-entry-audit-log/api-time-entry-audit-log-get-plain';
import { ApiTimeEntryAuditLogGet$Plain$Params } from '../fn/time-entry-audit-log/api-time-entry-audit-log-get-plain';
import { apiTimeEntryAuditLogIdGet$Json } from '../fn/time-entry-audit-log/api-time-entry-audit-log-id-get-json';
import { ApiTimeEntryAuditLogIdGet$Json$Params } from '../fn/time-entry-audit-log/api-time-entry-audit-log-id-get-json';
import { apiTimeEntryAuditLogIdGet$Plain } from '../fn/time-entry-audit-log/api-time-entry-audit-log-id-get-plain';
import { ApiTimeEntryAuditLogIdGet$Plain$Params } from '../fn/time-entry-audit-log/api-time-entry-audit-log-id-get-plain';
import { TimeEntryAuditLog } from '../models/time-entry-audit-log';

@Injectable({ providedIn: 'root' })
export class TimeEntryAuditLogService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `apiTimeEntryAuditLogGet()` */
  static readonly ApiTimeEntryAuditLogGetPath = '/api/TimeEntryAuditLog';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiTimeEntryAuditLogGet$Plain()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiTimeEntryAuditLogGet$Plain$Response(params?: ApiTimeEntryAuditLogGet$Plain$Params, context?: HttpContext): Promise<StrictHttpResponse<Array<TimeEntryAuditLog>>> {
    const obs = apiTimeEntryAuditLogGet$Plain(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiTimeEntryAuditLogGet$Plain$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiTimeEntryAuditLogGet$Plain(params?: ApiTimeEntryAuditLogGet$Plain$Params, context?: HttpContext): Promise<Array<TimeEntryAuditLog>> {
    const resp = this.apiTimeEntryAuditLogGet$Plain$Response(params, context);
    return resp.then((r: StrictHttpResponse<Array<TimeEntryAuditLog>>): Array<TimeEntryAuditLog> => r.body);
  }

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiTimeEntryAuditLogGet$Json()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiTimeEntryAuditLogGet$Json$Response(params?: ApiTimeEntryAuditLogGet$Json$Params, context?: HttpContext): Promise<StrictHttpResponse<Array<TimeEntryAuditLog>>> {
    const obs = apiTimeEntryAuditLogGet$Json(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiTimeEntryAuditLogGet$Json$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiTimeEntryAuditLogGet$Json(params?: ApiTimeEntryAuditLogGet$Json$Params, context?: HttpContext): Promise<Array<TimeEntryAuditLog>> {
    const resp = this.apiTimeEntryAuditLogGet$Json$Response(params, context);
    return resp.then((r: StrictHttpResponse<Array<TimeEntryAuditLog>>): Array<TimeEntryAuditLog> => r.body);
  }

  /** Path part for operation `apiTimeEntryAuditLogIdGet()` */
  static readonly ApiTimeEntryAuditLogIdGetPath = '/api/TimeEntryAuditLog/{id}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiTimeEntryAuditLogIdGet$Plain()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiTimeEntryAuditLogIdGet$Plain$Response(params: ApiTimeEntryAuditLogIdGet$Plain$Params, context?: HttpContext): Promise<StrictHttpResponse<TimeEntryAuditLog>> {
    const obs = apiTimeEntryAuditLogIdGet$Plain(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiTimeEntryAuditLogIdGet$Plain$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiTimeEntryAuditLogIdGet$Plain(params: ApiTimeEntryAuditLogIdGet$Plain$Params, context?: HttpContext): Promise<TimeEntryAuditLog> {
    const resp = this.apiTimeEntryAuditLogIdGet$Plain$Response(params, context);
    return resp.then((r: StrictHttpResponse<TimeEntryAuditLog>): TimeEntryAuditLog => r.body);
  }

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiTimeEntryAuditLogIdGet$Json()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiTimeEntryAuditLogIdGet$Json$Response(params: ApiTimeEntryAuditLogIdGet$Json$Params, context?: HttpContext): Promise<StrictHttpResponse<TimeEntryAuditLog>> {
    const obs = apiTimeEntryAuditLogIdGet$Json(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiTimeEntryAuditLogIdGet$Json$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiTimeEntryAuditLogIdGet$Json(params: ApiTimeEntryAuditLogIdGet$Json$Params, context?: HttpContext): Promise<TimeEntryAuditLog> {
    const resp = this.apiTimeEntryAuditLogIdGet$Json$Response(params, context);
    return resp.then((r: StrictHttpResponse<TimeEntryAuditLog>): TimeEntryAuditLog => r.body);
  }

}
