/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { firstValueFrom } from 'rxjs';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { apiTimeEntryCorrectionRequestGet$Json } from '../fn/time-entry-correction-request/api-time-entry-correction-request-get-json';
import { ApiTimeEntryCorrectionRequestGet$Json$Params } from '../fn/time-entry-correction-request/api-time-entry-correction-request-get-json';
import { apiTimeEntryCorrectionRequestGet$Plain } from '../fn/time-entry-correction-request/api-time-entry-correction-request-get-plain';
import { ApiTimeEntryCorrectionRequestGet$Plain$Params } from '../fn/time-entry-correction-request/api-time-entry-correction-request-get-plain';
import { apiTimeEntryCorrectionRequestIdApprovePut$Json } from '../fn/time-entry-correction-request/api-time-entry-correction-request-id-approve-put-json';
import { ApiTimeEntryCorrectionRequestIdApprovePut$Json$Params } from '../fn/time-entry-correction-request/api-time-entry-correction-request-id-approve-put-json';
import { apiTimeEntryCorrectionRequestIdApprovePut$Plain } from '../fn/time-entry-correction-request/api-time-entry-correction-request-id-approve-put-plain';
import { ApiTimeEntryCorrectionRequestIdApprovePut$Plain$Params } from '../fn/time-entry-correction-request/api-time-entry-correction-request-id-approve-put-plain';
import { apiTimeEntryCorrectionRequestIdGet$Json } from '../fn/time-entry-correction-request/api-time-entry-correction-request-id-get-json';
import { ApiTimeEntryCorrectionRequestIdGet$Json$Params } from '../fn/time-entry-correction-request/api-time-entry-correction-request-id-get-json';
import { apiTimeEntryCorrectionRequestIdGet$Plain } from '../fn/time-entry-correction-request/api-time-entry-correction-request-id-get-plain';
import { ApiTimeEntryCorrectionRequestIdGet$Plain$Params } from '../fn/time-entry-correction-request/api-time-entry-correction-request-id-get-plain';
import { apiTimeEntryCorrectionRequestIdRejectPut$Json } from '../fn/time-entry-correction-request/api-time-entry-correction-request-id-reject-put-json';
import { ApiTimeEntryCorrectionRequestIdRejectPut$Json$Params } from '../fn/time-entry-correction-request/api-time-entry-correction-request-id-reject-put-json';
import { apiTimeEntryCorrectionRequestIdRejectPut$Plain } from '../fn/time-entry-correction-request/api-time-entry-correction-request-id-reject-put-plain';
import { ApiTimeEntryCorrectionRequestIdRejectPut$Plain$Params } from '../fn/time-entry-correction-request/api-time-entry-correction-request-id-reject-put-plain';
import { apiTimeEntryCorrectionRequestMineGet$Json } from '../fn/time-entry-correction-request/api-time-entry-correction-request-mine-get-json';
import { ApiTimeEntryCorrectionRequestMineGet$Json$Params } from '../fn/time-entry-correction-request/api-time-entry-correction-request-mine-get-json';
import { apiTimeEntryCorrectionRequestMineGet$Plain } from '../fn/time-entry-correction-request/api-time-entry-correction-request-mine-get-plain';
import { ApiTimeEntryCorrectionRequestMineGet$Plain$Params } from '../fn/time-entry-correction-request/api-time-entry-correction-request-mine-get-plain';
import { apiTimeEntryCorrectionRequestPendingGet$Json } from '../fn/time-entry-correction-request/api-time-entry-correction-request-pending-get-json';
import { ApiTimeEntryCorrectionRequestPendingGet$Json$Params } from '../fn/time-entry-correction-request/api-time-entry-correction-request-pending-get-json';
import { apiTimeEntryCorrectionRequestPendingGet$Plain } from '../fn/time-entry-correction-request/api-time-entry-correction-request-pending-get-plain';
import { ApiTimeEntryCorrectionRequestPendingGet$Plain$Params } from '../fn/time-entry-correction-request/api-time-entry-correction-request-pending-get-plain';
import { apiTimeEntryCorrectionRequestPost$Json } from '../fn/time-entry-correction-request/api-time-entry-correction-request-post-json';
import { ApiTimeEntryCorrectionRequestPost$Json$Params } from '../fn/time-entry-correction-request/api-time-entry-correction-request-post-json';
import { apiTimeEntryCorrectionRequestPost$Plain } from '../fn/time-entry-correction-request/api-time-entry-correction-request-post-plain';
import { ApiTimeEntryCorrectionRequestPost$Plain$Params } from '../fn/time-entry-correction-request/api-time-entry-correction-request-post-plain';
import { CorrectionRequestDto } from '../models/correction-request-dto';
import { TimeEntryCorrectionRequest } from '../models/time-entry-correction-request';

@Injectable({ providedIn: 'root' })
export class TimeEntryCorrectionRequestService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `apiTimeEntryCorrectionRequestGet()` */
  static readonly ApiTimeEntryCorrectionRequestGetPath = '/api/TimeEntryCorrectionRequest';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiTimeEntryCorrectionRequestGet$Plain()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiTimeEntryCorrectionRequestGet$Plain$Response(params?: ApiTimeEntryCorrectionRequestGet$Plain$Params, context?: HttpContext): Promise<StrictHttpResponse<Array<TimeEntryCorrectionRequest>>> {
    const obs = apiTimeEntryCorrectionRequestGet$Plain(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiTimeEntryCorrectionRequestGet$Plain$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiTimeEntryCorrectionRequestGet$Plain(params?: ApiTimeEntryCorrectionRequestGet$Plain$Params, context?: HttpContext): Promise<Array<TimeEntryCorrectionRequest>> {
    const resp = this.apiTimeEntryCorrectionRequestGet$Plain$Response(params, context);
    return resp.then((r: StrictHttpResponse<Array<TimeEntryCorrectionRequest>>): Array<TimeEntryCorrectionRequest> => r.body);
  }

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiTimeEntryCorrectionRequestGet$Json()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiTimeEntryCorrectionRequestGet$Json$Response(params?: ApiTimeEntryCorrectionRequestGet$Json$Params, context?: HttpContext): Promise<StrictHttpResponse<Array<TimeEntryCorrectionRequest>>> {
    const obs = apiTimeEntryCorrectionRequestGet$Json(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiTimeEntryCorrectionRequestGet$Json$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiTimeEntryCorrectionRequestGet$Json(params?: ApiTimeEntryCorrectionRequestGet$Json$Params, context?: HttpContext): Promise<Array<TimeEntryCorrectionRequest>> {
    const resp = this.apiTimeEntryCorrectionRequestGet$Json$Response(params, context);
    return resp.then((r: StrictHttpResponse<Array<TimeEntryCorrectionRequest>>): Array<TimeEntryCorrectionRequest> => r.body);
  }

  /** Path part for operation `apiTimeEntryCorrectionRequestPost()` */
  static readonly ApiTimeEntryCorrectionRequestPostPath = '/api/TimeEntryCorrectionRequest';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiTimeEntryCorrectionRequestPost$Plain()` instead.
   *
   * This method sends `application/*+json` and handles request body of type `application/*+json`.
   */
  apiTimeEntryCorrectionRequestPost$Plain$Response(params: ApiTimeEntryCorrectionRequestPost$Plain$Params, context?: HttpContext): Promise<StrictHttpResponse<TimeEntryCorrectionRequest>> {
    const obs = apiTimeEntryCorrectionRequestPost$Plain(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiTimeEntryCorrectionRequestPost$Plain$Response()` instead.
   *
   * This method sends `application/*+json` and handles request body of type `application/*+json`.
   */
  apiTimeEntryCorrectionRequestPost$Plain(params: ApiTimeEntryCorrectionRequestPost$Plain$Params, context?: HttpContext): Promise<TimeEntryCorrectionRequest> {
    const resp = this.apiTimeEntryCorrectionRequestPost$Plain$Response(params, context);
    return resp.then((r: StrictHttpResponse<TimeEntryCorrectionRequest>): TimeEntryCorrectionRequest => r.body);
  }

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiTimeEntryCorrectionRequestPost$Json()` instead.
   *
   * This method sends `application/*+json` and handles request body of type `application/*+json`.
   */
  apiTimeEntryCorrectionRequestPost$Json$Response(params: ApiTimeEntryCorrectionRequestPost$Json$Params, context?: HttpContext): Promise<StrictHttpResponse<TimeEntryCorrectionRequest>> {
    const obs = apiTimeEntryCorrectionRequestPost$Json(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiTimeEntryCorrectionRequestPost$Json$Response()` instead.
   *
   * This method sends `application/*+json` and handles request body of type `application/*+json`.
   */
  apiTimeEntryCorrectionRequestPost$Json(params: ApiTimeEntryCorrectionRequestPost$Json$Params, context?: HttpContext): Promise<TimeEntryCorrectionRequest> {
    const resp = this.apiTimeEntryCorrectionRequestPost$Json$Response(params, context);
    return resp.then((r: StrictHttpResponse<TimeEntryCorrectionRequest>): TimeEntryCorrectionRequest => r.body);
  }

  /** Path part for operation `apiTimeEntryCorrectionRequestMineGet()` */
  static readonly ApiTimeEntryCorrectionRequestMineGetPath = '/api/TimeEntryCorrectionRequest/mine';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiTimeEntryCorrectionRequestMineGet$Plain()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiTimeEntryCorrectionRequestMineGet$Plain$Response(params?: ApiTimeEntryCorrectionRequestMineGet$Plain$Params, context?: HttpContext): Promise<StrictHttpResponse<Array<CorrectionRequestDto>>> {
    const obs = apiTimeEntryCorrectionRequestMineGet$Plain(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiTimeEntryCorrectionRequestMineGet$Plain$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiTimeEntryCorrectionRequestMineGet$Plain(params?: ApiTimeEntryCorrectionRequestMineGet$Plain$Params, context?: HttpContext): Promise<Array<CorrectionRequestDto>> {
    const resp = this.apiTimeEntryCorrectionRequestMineGet$Plain$Response(params, context);
    return resp.then((r: StrictHttpResponse<Array<CorrectionRequestDto>>): Array<CorrectionRequestDto> => r.body);
  }

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiTimeEntryCorrectionRequestMineGet$Json()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiTimeEntryCorrectionRequestMineGet$Json$Response(params?: ApiTimeEntryCorrectionRequestMineGet$Json$Params, context?: HttpContext): Promise<StrictHttpResponse<Array<CorrectionRequestDto>>> {
    const obs = apiTimeEntryCorrectionRequestMineGet$Json(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiTimeEntryCorrectionRequestMineGet$Json$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiTimeEntryCorrectionRequestMineGet$Json(params?: ApiTimeEntryCorrectionRequestMineGet$Json$Params, context?: HttpContext): Promise<Array<CorrectionRequestDto>> {
    const resp = this.apiTimeEntryCorrectionRequestMineGet$Json$Response(params, context);
    return resp.then((r: StrictHttpResponse<Array<CorrectionRequestDto>>): Array<CorrectionRequestDto> => r.body);
  }

  /** Path part for operation `apiTimeEntryCorrectionRequestPendingGet()` */
  static readonly ApiTimeEntryCorrectionRequestPendingGetPath = '/api/TimeEntryCorrectionRequest/pending';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiTimeEntryCorrectionRequestPendingGet$Plain()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiTimeEntryCorrectionRequestPendingGet$Plain$Response(params?: ApiTimeEntryCorrectionRequestPendingGet$Plain$Params, context?: HttpContext): Promise<StrictHttpResponse<Array<CorrectionRequestDto>>> {
    const obs = apiTimeEntryCorrectionRequestPendingGet$Plain(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiTimeEntryCorrectionRequestPendingGet$Plain$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiTimeEntryCorrectionRequestPendingGet$Plain(params?: ApiTimeEntryCorrectionRequestPendingGet$Plain$Params, context?: HttpContext): Promise<Array<CorrectionRequestDto>> {
    const resp = this.apiTimeEntryCorrectionRequestPendingGet$Plain$Response(params, context);
    return resp.then((r: StrictHttpResponse<Array<CorrectionRequestDto>>): Array<CorrectionRequestDto> => r.body);
  }

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiTimeEntryCorrectionRequestPendingGet$Json()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiTimeEntryCorrectionRequestPendingGet$Json$Response(params?: ApiTimeEntryCorrectionRequestPendingGet$Json$Params, context?: HttpContext): Promise<StrictHttpResponse<Array<CorrectionRequestDto>>> {
    const obs = apiTimeEntryCorrectionRequestPendingGet$Json(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiTimeEntryCorrectionRequestPendingGet$Json$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiTimeEntryCorrectionRequestPendingGet$Json(params?: ApiTimeEntryCorrectionRequestPendingGet$Json$Params, context?: HttpContext): Promise<Array<CorrectionRequestDto>> {
    const resp = this.apiTimeEntryCorrectionRequestPendingGet$Json$Response(params, context);
    return resp.then((r: StrictHttpResponse<Array<CorrectionRequestDto>>): Array<CorrectionRequestDto> => r.body);
  }

  /** Path part for operation `apiTimeEntryCorrectionRequestIdGet()` */
  static readonly ApiTimeEntryCorrectionRequestIdGetPath = '/api/TimeEntryCorrectionRequest/{id}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiTimeEntryCorrectionRequestIdGet$Plain()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiTimeEntryCorrectionRequestIdGet$Plain$Response(params: ApiTimeEntryCorrectionRequestIdGet$Plain$Params, context?: HttpContext): Promise<StrictHttpResponse<TimeEntryCorrectionRequest>> {
    const obs = apiTimeEntryCorrectionRequestIdGet$Plain(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiTimeEntryCorrectionRequestIdGet$Plain$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiTimeEntryCorrectionRequestIdGet$Plain(params: ApiTimeEntryCorrectionRequestIdGet$Plain$Params, context?: HttpContext): Promise<TimeEntryCorrectionRequest> {
    const resp = this.apiTimeEntryCorrectionRequestIdGet$Plain$Response(params, context);
    return resp.then((r: StrictHttpResponse<TimeEntryCorrectionRequest>): TimeEntryCorrectionRequest => r.body);
  }

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiTimeEntryCorrectionRequestIdGet$Json()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiTimeEntryCorrectionRequestIdGet$Json$Response(params: ApiTimeEntryCorrectionRequestIdGet$Json$Params, context?: HttpContext): Promise<StrictHttpResponse<TimeEntryCorrectionRequest>> {
    const obs = apiTimeEntryCorrectionRequestIdGet$Json(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiTimeEntryCorrectionRequestIdGet$Json$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiTimeEntryCorrectionRequestIdGet$Json(params: ApiTimeEntryCorrectionRequestIdGet$Json$Params, context?: HttpContext): Promise<TimeEntryCorrectionRequest> {
    const resp = this.apiTimeEntryCorrectionRequestIdGet$Json$Response(params, context);
    return resp.then((r: StrictHttpResponse<TimeEntryCorrectionRequest>): TimeEntryCorrectionRequest => r.body);
  }

  /** Path part for operation `apiTimeEntryCorrectionRequestIdApprovePut()` */
  static readonly ApiTimeEntryCorrectionRequestIdApprovePutPath = '/api/TimeEntryCorrectionRequest/{id}/approve';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiTimeEntryCorrectionRequestIdApprovePut$Plain()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiTimeEntryCorrectionRequestIdApprovePut$Plain$Response(params: ApiTimeEntryCorrectionRequestIdApprovePut$Plain$Params, context?: HttpContext): Promise<StrictHttpResponse<TimeEntryCorrectionRequest>> {
    const obs = apiTimeEntryCorrectionRequestIdApprovePut$Plain(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiTimeEntryCorrectionRequestIdApprovePut$Plain$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiTimeEntryCorrectionRequestIdApprovePut$Plain(params: ApiTimeEntryCorrectionRequestIdApprovePut$Plain$Params, context?: HttpContext): Promise<TimeEntryCorrectionRequest> {
    const resp = this.apiTimeEntryCorrectionRequestIdApprovePut$Plain$Response(params, context);
    return resp.then((r: StrictHttpResponse<TimeEntryCorrectionRequest>): TimeEntryCorrectionRequest => r.body);
  }

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiTimeEntryCorrectionRequestIdApprovePut$Json()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiTimeEntryCorrectionRequestIdApprovePut$Json$Response(params: ApiTimeEntryCorrectionRequestIdApprovePut$Json$Params, context?: HttpContext): Promise<StrictHttpResponse<TimeEntryCorrectionRequest>> {
    const obs = apiTimeEntryCorrectionRequestIdApprovePut$Json(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiTimeEntryCorrectionRequestIdApprovePut$Json$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiTimeEntryCorrectionRequestIdApprovePut$Json(params: ApiTimeEntryCorrectionRequestIdApprovePut$Json$Params, context?: HttpContext): Promise<TimeEntryCorrectionRequest> {
    const resp = this.apiTimeEntryCorrectionRequestIdApprovePut$Json$Response(params, context);
    return resp.then((r: StrictHttpResponse<TimeEntryCorrectionRequest>): TimeEntryCorrectionRequest => r.body);
  }

  /** Path part for operation `apiTimeEntryCorrectionRequestIdRejectPut()` */
  static readonly ApiTimeEntryCorrectionRequestIdRejectPutPath = '/api/TimeEntryCorrectionRequest/{id}/reject';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiTimeEntryCorrectionRequestIdRejectPut$Plain()` instead.
   *
   * This method sends `application/*+json` and handles request body of type `application/*+json`.
   */
  apiTimeEntryCorrectionRequestIdRejectPut$Plain$Response(params: ApiTimeEntryCorrectionRequestIdRejectPut$Plain$Params, context?: HttpContext): Promise<StrictHttpResponse<TimeEntryCorrectionRequest>> {
    const obs = apiTimeEntryCorrectionRequestIdRejectPut$Plain(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiTimeEntryCorrectionRequestIdRejectPut$Plain$Response()` instead.
   *
   * This method sends `application/*+json` and handles request body of type `application/*+json`.
   */
  apiTimeEntryCorrectionRequestIdRejectPut$Plain(params: ApiTimeEntryCorrectionRequestIdRejectPut$Plain$Params, context?: HttpContext): Promise<TimeEntryCorrectionRequest> {
    const resp = this.apiTimeEntryCorrectionRequestIdRejectPut$Plain$Response(params, context);
    return resp.then((r: StrictHttpResponse<TimeEntryCorrectionRequest>): TimeEntryCorrectionRequest => r.body);
  }

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiTimeEntryCorrectionRequestIdRejectPut$Json()` instead.
   *
   * This method sends `application/*+json` and handles request body of type `application/*+json`.
   */
  apiTimeEntryCorrectionRequestIdRejectPut$Json$Response(params: ApiTimeEntryCorrectionRequestIdRejectPut$Json$Params, context?: HttpContext): Promise<StrictHttpResponse<TimeEntryCorrectionRequest>> {
    const obs = apiTimeEntryCorrectionRequestIdRejectPut$Json(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiTimeEntryCorrectionRequestIdRejectPut$Json$Response()` instead.
   *
   * This method sends `application/*+json` and handles request body of type `application/*+json`.
   */
  apiTimeEntryCorrectionRequestIdRejectPut$Json(params: ApiTimeEntryCorrectionRequestIdRejectPut$Json$Params, context?: HttpContext): Promise<TimeEntryCorrectionRequest> {
    const resp = this.apiTimeEntryCorrectionRequestIdRejectPut$Json$Response(params, context);
    return resp.then((r: StrictHttpResponse<TimeEntryCorrectionRequest>): TimeEntryCorrectionRequest => r.body);
  }

}
