/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { firstValueFrom } from 'rxjs';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { apiTimeEntryGet$Json } from '../fn/time-entry/api-time-entry-get-json';
import { ApiTimeEntryGet$Json$Params } from '../fn/time-entry/api-time-entry-get-json';
import { apiTimeEntryGet$Plain } from '../fn/time-entry/api-time-entry-get-plain';
import { ApiTimeEntryGet$Plain$Params } from '../fn/time-entry/api-time-entry-get-plain';
import { apiTimeEntryIdBreaksBreakIdStopPut$Json } from '../fn/time-entry/api-time-entry-id-breaks-break-id-stop-put-json';
import { ApiTimeEntryIdBreaksBreakIdStopPut$Json$Params } from '../fn/time-entry/api-time-entry-id-breaks-break-id-stop-put-json';
import { apiTimeEntryIdBreaksBreakIdStopPut$Plain } from '../fn/time-entry/api-time-entry-id-breaks-break-id-stop-put-plain';
import { ApiTimeEntryIdBreaksBreakIdStopPut$Plain$Params } from '../fn/time-entry/api-time-entry-id-breaks-break-id-stop-put-plain';
import { apiTimeEntryIdBreaksPost$Json } from '../fn/time-entry/api-time-entry-id-breaks-post-json';
import { ApiTimeEntryIdBreaksPost$Json$Params } from '../fn/time-entry/api-time-entry-id-breaks-post-json';
import { apiTimeEntryIdBreaksPost$Plain } from '../fn/time-entry/api-time-entry-id-breaks-post-plain';
import { ApiTimeEntryIdBreaksPost$Plain$Params } from '../fn/time-entry/api-time-entry-id-breaks-post-plain';
import { apiTimeEntryIdDelete } from '../fn/time-entry/api-time-entry-id-delete';
import { ApiTimeEntryIdDelete$Params } from '../fn/time-entry/api-time-entry-id-delete';
import { apiTimeEntryIdGet$Json } from '../fn/time-entry/api-time-entry-id-get-json';
import { ApiTimeEntryIdGet$Json$Params } from '../fn/time-entry/api-time-entry-id-get-json';
import { apiTimeEntryIdGet$Plain } from '../fn/time-entry/api-time-entry-id-get-plain';
import { ApiTimeEntryIdGet$Plain$Params } from '../fn/time-entry/api-time-entry-id-get-plain';
import { apiTimeEntryIdPut$Json } from '../fn/time-entry/api-time-entry-id-put-json';
import { ApiTimeEntryIdPut$Json$Params } from '../fn/time-entry/api-time-entry-id-put-json';
import { apiTimeEntryIdPut$Plain } from '../fn/time-entry/api-time-entry-id-put-plain';
import { ApiTimeEntryIdPut$Plain$Params } from '../fn/time-entry/api-time-entry-id-put-plain';
import { apiTimeEntryIdStopPost$Json } from '../fn/time-entry/api-time-entry-id-stop-post-json';
import { ApiTimeEntryIdStopPost$Json$Params } from '../fn/time-entry/api-time-entry-id-stop-post-json';
import { apiTimeEntryIdStopPost$Plain } from '../fn/time-entry/api-time-entry-id-stop-post-plain';
import { ApiTimeEntryIdStopPost$Plain$Params } from '../fn/time-entry/api-time-entry-id-stop-post-plain';
import { apiTimeEntryMineGet$Json } from '../fn/time-entry/api-time-entry-mine-get-json';
import { ApiTimeEntryMineGet$Json$Params } from '../fn/time-entry/api-time-entry-mine-get-json';
import { apiTimeEntryMineGet$Plain } from '../fn/time-entry/api-time-entry-mine-get-plain';
import { ApiTimeEntryMineGet$Plain$Params } from '../fn/time-entry/api-time-entry-mine-get-plain';
import { apiTimeEntryPost$Json } from '../fn/time-entry/api-time-entry-post-json';
import { ApiTimeEntryPost$Json$Params } from '../fn/time-entry/api-time-entry-post-json';
import { apiTimeEntryPost$Plain } from '../fn/time-entry/api-time-entry-post-plain';
import { ApiTimeEntryPost$Plain$Params } from '../fn/time-entry/api-time-entry-post-plain';
import { apiTimeEntryStartPost$Json } from '../fn/time-entry/api-time-entry-start-post-json';
import { ApiTimeEntryStartPost$Json$Params } from '../fn/time-entry/api-time-entry-start-post-json';
import { apiTimeEntryStartPost$Plain } from '../fn/time-entry/api-time-entry-start-post-plain';
import { ApiTimeEntryStartPost$Plain$Params } from '../fn/time-entry/api-time-entry-start-post-plain';
import { apiTimeEntryTeamGet$Json } from '../fn/time-entry/api-time-entry-team-get-json';
import { ApiTimeEntryTeamGet$Json$Params } from '../fn/time-entry/api-time-entry-team-get-json';
import { apiTimeEntryTeamGet$Plain } from '../fn/time-entry/api-time-entry-team-get-plain';
import { ApiTimeEntryTeamGet$Plain$Params } from '../fn/time-entry/api-time-entry-team-get-plain';
import { TimeEntry } from '../models/time-entry';
import { TimeEntryBreak } from '../models/time-entry-break';

@Injectable({ providedIn: 'root' })
export class TimeEntryService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `apiTimeEntryGet()` */
  static readonly ApiTimeEntryGetPath = '/api/TimeEntry';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiTimeEntryGet$Plain()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiTimeEntryGet$Plain$Response(params?: ApiTimeEntryGet$Plain$Params, context?: HttpContext): Promise<StrictHttpResponse<Array<TimeEntry>>> {
    const obs = apiTimeEntryGet$Plain(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiTimeEntryGet$Plain$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiTimeEntryGet$Plain(params?: ApiTimeEntryGet$Plain$Params, context?: HttpContext): Promise<Array<TimeEntry>> {
    const resp = this.apiTimeEntryGet$Plain$Response(params, context);
    return resp.then((r: StrictHttpResponse<Array<TimeEntry>>): Array<TimeEntry> => r.body);
  }

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiTimeEntryGet$Json()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiTimeEntryGet$Json$Response(params?: ApiTimeEntryGet$Json$Params, context?: HttpContext): Promise<StrictHttpResponse<Array<TimeEntry>>> {
    const obs = apiTimeEntryGet$Json(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiTimeEntryGet$Json$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiTimeEntryGet$Json(params?: ApiTimeEntryGet$Json$Params, context?: HttpContext): Promise<Array<TimeEntry>> {
    const resp = this.apiTimeEntryGet$Json$Response(params, context);
    return resp.then((r: StrictHttpResponse<Array<TimeEntry>>): Array<TimeEntry> => r.body);
  }

  /** Path part for operation `apiTimeEntryPost()` */
  static readonly ApiTimeEntryPostPath = '/api/TimeEntry';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiTimeEntryPost$Plain()` instead.
   *
   * This method sends `application/*+json` and handles request body of type `application/*+json`.
   */
  apiTimeEntryPost$Plain$Response(params: ApiTimeEntryPost$Plain$Params, context?: HttpContext): Promise<StrictHttpResponse<TimeEntry>> {
    const obs = apiTimeEntryPost$Plain(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiTimeEntryPost$Plain$Response()` instead.
   *
   * This method sends `application/*+json` and handles request body of type `application/*+json`.
   */
  apiTimeEntryPost$Plain(params: ApiTimeEntryPost$Plain$Params, context?: HttpContext): Promise<TimeEntry> {
    const resp = this.apiTimeEntryPost$Plain$Response(params, context);
    return resp.then((r: StrictHttpResponse<TimeEntry>): TimeEntry => r.body);
  }

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiTimeEntryPost$Json()` instead.
   *
   * This method sends `application/*+json` and handles request body of type `application/*+json`.
   */
  apiTimeEntryPost$Json$Response(params: ApiTimeEntryPost$Json$Params, context?: HttpContext): Promise<StrictHttpResponse<TimeEntry>> {
    const obs = apiTimeEntryPost$Json(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiTimeEntryPost$Json$Response()` instead.
   *
   * This method sends `application/*+json` and handles request body of type `application/*+json`.
   */
  apiTimeEntryPost$Json(params: ApiTimeEntryPost$Json$Params, context?: HttpContext): Promise<TimeEntry> {
    const resp = this.apiTimeEntryPost$Json$Response(params, context);
    return resp.then((r: StrictHttpResponse<TimeEntry>): TimeEntry => r.body);
  }

  /** Path part for operation `apiTimeEntryMineGet()` */
  static readonly ApiTimeEntryMineGetPath = '/api/TimeEntry/mine';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiTimeEntryMineGet$Plain()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiTimeEntryMineGet$Plain$Response(params?: ApiTimeEntryMineGet$Plain$Params, context?: HttpContext): Promise<StrictHttpResponse<Array<TimeEntry>>> {
    const obs = apiTimeEntryMineGet$Plain(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiTimeEntryMineGet$Plain$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiTimeEntryMineGet$Plain(params?: ApiTimeEntryMineGet$Plain$Params, context?: HttpContext): Promise<Array<TimeEntry>> {
    const resp = this.apiTimeEntryMineGet$Plain$Response(params, context);
    return resp.then((r: StrictHttpResponse<Array<TimeEntry>>): Array<TimeEntry> => r.body);
  }

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiTimeEntryMineGet$Json()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiTimeEntryMineGet$Json$Response(params?: ApiTimeEntryMineGet$Json$Params, context?: HttpContext): Promise<StrictHttpResponse<Array<TimeEntry>>> {
    const obs = apiTimeEntryMineGet$Json(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiTimeEntryMineGet$Json$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiTimeEntryMineGet$Json(params?: ApiTimeEntryMineGet$Json$Params, context?: HttpContext): Promise<Array<TimeEntry>> {
    const resp = this.apiTimeEntryMineGet$Json$Response(params, context);
    return resp.then((r: StrictHttpResponse<Array<TimeEntry>>): Array<TimeEntry> => r.body);
  }

  /** Path part for operation `apiTimeEntryTeamGet()` */
  static readonly ApiTimeEntryTeamGetPath = '/api/TimeEntry/team';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiTimeEntryTeamGet$Plain()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiTimeEntryTeamGet$Plain$Response(params?: ApiTimeEntryTeamGet$Plain$Params, context?: HttpContext): Promise<StrictHttpResponse<Array<TimeEntry>>> {
    const obs = apiTimeEntryTeamGet$Plain(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiTimeEntryTeamGet$Plain$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiTimeEntryTeamGet$Plain(params?: ApiTimeEntryTeamGet$Plain$Params, context?: HttpContext): Promise<Array<TimeEntry>> {
    const resp = this.apiTimeEntryTeamGet$Plain$Response(params, context);
    return resp.then((r: StrictHttpResponse<Array<TimeEntry>>): Array<TimeEntry> => r.body);
  }

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiTimeEntryTeamGet$Json()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiTimeEntryTeamGet$Json$Response(params?: ApiTimeEntryTeamGet$Json$Params, context?: HttpContext): Promise<StrictHttpResponse<Array<TimeEntry>>> {
    const obs = apiTimeEntryTeamGet$Json(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiTimeEntryTeamGet$Json$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiTimeEntryTeamGet$Json(params?: ApiTimeEntryTeamGet$Json$Params, context?: HttpContext): Promise<Array<TimeEntry>> {
    const resp = this.apiTimeEntryTeamGet$Json$Response(params, context);
    return resp.then((r: StrictHttpResponse<Array<TimeEntry>>): Array<TimeEntry> => r.body);
  }

  /** Path part for operation `apiTimeEntryIdGet()` */
  static readonly ApiTimeEntryIdGetPath = '/api/TimeEntry/{id}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiTimeEntryIdGet$Plain()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiTimeEntryIdGet$Plain$Response(params: ApiTimeEntryIdGet$Plain$Params, context?: HttpContext): Promise<StrictHttpResponse<TimeEntry>> {
    const obs = apiTimeEntryIdGet$Plain(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiTimeEntryIdGet$Plain$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiTimeEntryIdGet$Plain(params: ApiTimeEntryIdGet$Plain$Params, context?: HttpContext): Promise<TimeEntry> {
    const resp = this.apiTimeEntryIdGet$Plain$Response(params, context);
    return resp.then((r: StrictHttpResponse<TimeEntry>): TimeEntry => r.body);
  }

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiTimeEntryIdGet$Json()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiTimeEntryIdGet$Json$Response(params: ApiTimeEntryIdGet$Json$Params, context?: HttpContext): Promise<StrictHttpResponse<TimeEntry>> {
    const obs = apiTimeEntryIdGet$Json(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiTimeEntryIdGet$Json$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiTimeEntryIdGet$Json(params: ApiTimeEntryIdGet$Json$Params, context?: HttpContext): Promise<TimeEntry> {
    const resp = this.apiTimeEntryIdGet$Json$Response(params, context);
    return resp.then((r: StrictHttpResponse<TimeEntry>): TimeEntry => r.body);
  }

  /** Path part for operation `apiTimeEntryIdPut()` */
  static readonly ApiTimeEntryIdPutPath = '/api/TimeEntry/{id}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiTimeEntryIdPut$Plain()` instead.
   *
   * This method sends `application/*+json` and handles request body of type `application/*+json`.
   */
  apiTimeEntryIdPut$Plain$Response(params: ApiTimeEntryIdPut$Plain$Params, context?: HttpContext): Promise<StrictHttpResponse<TimeEntry>> {
    const obs = apiTimeEntryIdPut$Plain(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiTimeEntryIdPut$Plain$Response()` instead.
   *
   * This method sends `application/*+json` and handles request body of type `application/*+json`.
   */
  apiTimeEntryIdPut$Plain(params: ApiTimeEntryIdPut$Plain$Params, context?: HttpContext): Promise<TimeEntry> {
    const resp = this.apiTimeEntryIdPut$Plain$Response(params, context);
    return resp.then((r: StrictHttpResponse<TimeEntry>): TimeEntry => r.body);
  }

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiTimeEntryIdPut$Json()` instead.
   *
   * This method sends `application/*+json` and handles request body of type `application/*+json`.
   */
  apiTimeEntryIdPut$Json$Response(params: ApiTimeEntryIdPut$Json$Params, context?: HttpContext): Promise<StrictHttpResponse<TimeEntry>> {
    const obs = apiTimeEntryIdPut$Json(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiTimeEntryIdPut$Json$Response()` instead.
   *
   * This method sends `application/*+json` and handles request body of type `application/*+json`.
   */
  apiTimeEntryIdPut$Json(params: ApiTimeEntryIdPut$Json$Params, context?: HttpContext): Promise<TimeEntry> {
    const resp = this.apiTimeEntryIdPut$Json$Response(params, context);
    return resp.then((r: StrictHttpResponse<TimeEntry>): TimeEntry => r.body);
  }

  /** Path part for operation `apiTimeEntryIdDelete()` */
  static readonly ApiTimeEntryIdDeletePath = '/api/TimeEntry/{id}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiTimeEntryIdDelete()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiTimeEntryIdDelete$Response(params: ApiTimeEntryIdDelete$Params, context?: HttpContext): Promise<StrictHttpResponse<void>> {
    const obs = apiTimeEntryIdDelete(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiTimeEntryIdDelete$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiTimeEntryIdDelete(params: ApiTimeEntryIdDelete$Params, context?: HttpContext): Promise<void> {
    const resp = this.apiTimeEntryIdDelete$Response(params, context);
    return resp.then((r: StrictHttpResponse<void>): void => r.body);
  }

  /** Path part for operation `apiTimeEntryStartPost()` */
  static readonly ApiTimeEntryStartPostPath = '/api/TimeEntry/start';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiTimeEntryStartPost$Plain()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiTimeEntryStartPost$Plain$Response(params?: ApiTimeEntryStartPost$Plain$Params, context?: HttpContext): Promise<StrictHttpResponse<TimeEntry>> {
    const obs = apiTimeEntryStartPost$Plain(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiTimeEntryStartPost$Plain$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiTimeEntryStartPost$Plain(params?: ApiTimeEntryStartPost$Plain$Params, context?: HttpContext): Promise<TimeEntry> {
    const resp = this.apiTimeEntryStartPost$Plain$Response(params, context);
    return resp.then((r: StrictHttpResponse<TimeEntry>): TimeEntry => r.body);
  }

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiTimeEntryStartPost$Json()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiTimeEntryStartPost$Json$Response(params?: ApiTimeEntryStartPost$Json$Params, context?: HttpContext): Promise<StrictHttpResponse<TimeEntry>> {
    const obs = apiTimeEntryStartPost$Json(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiTimeEntryStartPost$Json$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiTimeEntryStartPost$Json(params?: ApiTimeEntryStartPost$Json$Params, context?: HttpContext): Promise<TimeEntry> {
    const resp = this.apiTimeEntryStartPost$Json$Response(params, context);
    return resp.then((r: StrictHttpResponse<TimeEntry>): TimeEntry => r.body);
  }

  /** Path part for operation `apiTimeEntryIdStopPost()` */
  static readonly ApiTimeEntryIdStopPostPath = '/api/TimeEntry/{id}/stop';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiTimeEntryIdStopPost$Plain()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiTimeEntryIdStopPost$Plain$Response(params: ApiTimeEntryIdStopPost$Plain$Params, context?: HttpContext): Promise<StrictHttpResponse<TimeEntry>> {
    const obs = apiTimeEntryIdStopPost$Plain(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiTimeEntryIdStopPost$Plain$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiTimeEntryIdStopPost$Plain(params: ApiTimeEntryIdStopPost$Plain$Params, context?: HttpContext): Promise<TimeEntry> {
    const resp = this.apiTimeEntryIdStopPost$Plain$Response(params, context);
    return resp.then((r: StrictHttpResponse<TimeEntry>): TimeEntry => r.body);
  }

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiTimeEntryIdStopPost$Json()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiTimeEntryIdStopPost$Json$Response(params: ApiTimeEntryIdStopPost$Json$Params, context?: HttpContext): Promise<StrictHttpResponse<TimeEntry>> {
    const obs = apiTimeEntryIdStopPost$Json(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiTimeEntryIdStopPost$Json$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiTimeEntryIdStopPost$Json(params: ApiTimeEntryIdStopPost$Json$Params, context?: HttpContext): Promise<TimeEntry> {
    const resp = this.apiTimeEntryIdStopPost$Json$Response(params, context);
    return resp.then((r: StrictHttpResponse<TimeEntry>): TimeEntry => r.body);
  }

  /** Path part for operation `apiTimeEntryIdBreaksPost()` */
  static readonly ApiTimeEntryIdBreaksPostPath = '/api/TimeEntry/{id}/breaks';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiTimeEntryIdBreaksPost$Plain()` instead.
   *
   * This method sends `application/*+json` and handles request body of type `application/*+json`.
   */
  apiTimeEntryIdBreaksPost$Plain$Response(params: ApiTimeEntryIdBreaksPost$Plain$Params, context?: HttpContext): Promise<StrictHttpResponse<TimeEntryBreak>> {
    const obs = apiTimeEntryIdBreaksPost$Plain(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiTimeEntryIdBreaksPost$Plain$Response()` instead.
   *
   * This method sends `application/*+json` and handles request body of type `application/*+json`.
   */
  apiTimeEntryIdBreaksPost$Plain(params: ApiTimeEntryIdBreaksPost$Plain$Params, context?: HttpContext): Promise<TimeEntryBreak> {
    const resp = this.apiTimeEntryIdBreaksPost$Plain$Response(params, context);
    return resp.then((r: StrictHttpResponse<TimeEntryBreak>): TimeEntryBreak => r.body);
  }

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiTimeEntryIdBreaksPost$Json()` instead.
   *
   * This method sends `application/*+json` and handles request body of type `application/*+json`.
   */
  apiTimeEntryIdBreaksPost$Json$Response(params: ApiTimeEntryIdBreaksPost$Json$Params, context?: HttpContext): Promise<StrictHttpResponse<TimeEntryBreak>> {
    const obs = apiTimeEntryIdBreaksPost$Json(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiTimeEntryIdBreaksPost$Json$Response()` instead.
   *
   * This method sends `application/*+json` and handles request body of type `application/*+json`.
   */
  apiTimeEntryIdBreaksPost$Json(params: ApiTimeEntryIdBreaksPost$Json$Params, context?: HttpContext): Promise<TimeEntryBreak> {
    const resp = this.apiTimeEntryIdBreaksPost$Json$Response(params, context);
    return resp.then((r: StrictHttpResponse<TimeEntryBreak>): TimeEntryBreak => r.body);
  }

  /** Path part for operation `apiTimeEntryIdBreaksBreakIdStopPut()` */
  static readonly ApiTimeEntryIdBreaksBreakIdStopPutPath = '/api/TimeEntry/{id}/breaks/{breakId}/stop';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiTimeEntryIdBreaksBreakIdStopPut$Plain()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiTimeEntryIdBreaksBreakIdStopPut$Plain$Response(params: ApiTimeEntryIdBreaksBreakIdStopPut$Plain$Params, context?: HttpContext): Promise<StrictHttpResponse<TimeEntryBreak>> {
    const obs = apiTimeEntryIdBreaksBreakIdStopPut$Plain(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiTimeEntryIdBreaksBreakIdStopPut$Plain$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiTimeEntryIdBreaksBreakIdStopPut$Plain(params: ApiTimeEntryIdBreaksBreakIdStopPut$Plain$Params, context?: HttpContext): Promise<TimeEntryBreak> {
    const resp = this.apiTimeEntryIdBreaksBreakIdStopPut$Plain$Response(params, context);
    return resp.then((r: StrictHttpResponse<TimeEntryBreak>): TimeEntryBreak => r.body);
  }

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiTimeEntryIdBreaksBreakIdStopPut$Json()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiTimeEntryIdBreaksBreakIdStopPut$Json$Response(params: ApiTimeEntryIdBreaksBreakIdStopPut$Json$Params, context?: HttpContext): Promise<StrictHttpResponse<TimeEntryBreak>> {
    const obs = apiTimeEntryIdBreaksBreakIdStopPut$Json(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiTimeEntryIdBreaksBreakIdStopPut$Json$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiTimeEntryIdBreaksBreakIdStopPut$Json(params: ApiTimeEntryIdBreaksBreakIdStopPut$Json$Params, context?: HttpContext): Promise<TimeEntryBreak> {
    const resp = this.apiTimeEntryIdBreaksBreakIdStopPut$Json$Response(params, context);
    return resp.then((r: StrictHttpResponse<TimeEntryBreak>): TimeEntryBreak => r.body);
  }

}
