/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { firstValueFrom } from 'rxjs';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { apiUserInvitationGet$Json } from '../fn/user-invitation/api-user-invitation-get-json';
import { ApiUserInvitationGet$Json$Params } from '../fn/user-invitation/api-user-invitation-get-json';
import { apiUserInvitationGet$Plain } from '../fn/user-invitation/api-user-invitation-get-plain';
import { ApiUserInvitationGet$Plain$Params } from '../fn/user-invitation/api-user-invitation-get-plain';
import { apiUserInvitationIdArchivePost } from '../fn/user-invitation/api-user-invitation-id-archive-post';
import { ApiUserInvitationIdArchivePost$Params } from '../fn/user-invitation/api-user-invitation-id-archive-post';
import { apiUserInvitationPost$Json } from '../fn/user-invitation/api-user-invitation-post-json';
import { ApiUserInvitationPost$Json$Params } from '../fn/user-invitation/api-user-invitation-post-json';
import { apiUserInvitationPost$Plain } from '../fn/user-invitation/api-user-invitation-post-plain';
import { ApiUserInvitationPost$Plain$Params } from '../fn/user-invitation/api-user-invitation-post-plain';
import { InviteUserResponse } from '../models/invite-user-response';
import { UserInvitation } from '../models/user-invitation';

@Injectable({ providedIn: 'root' })
export class UserInvitationService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `apiUserInvitationGet()` */
  static readonly ApiUserInvitationGetPath = '/api/UserInvitation';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiUserInvitationGet$Plain()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiUserInvitationGet$Plain$Response(params?: ApiUserInvitationGet$Plain$Params, context?: HttpContext): Promise<StrictHttpResponse<Array<UserInvitation>>> {
    const obs = apiUserInvitationGet$Plain(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiUserInvitationGet$Plain$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiUserInvitationGet$Plain(params?: ApiUserInvitationGet$Plain$Params, context?: HttpContext): Promise<Array<UserInvitation>> {
    const resp = this.apiUserInvitationGet$Plain$Response(params, context);
    return resp.then((r: StrictHttpResponse<Array<UserInvitation>>): Array<UserInvitation> => r.body);
  }

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiUserInvitationGet$Json()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiUserInvitationGet$Json$Response(params?: ApiUserInvitationGet$Json$Params, context?: HttpContext): Promise<StrictHttpResponse<Array<UserInvitation>>> {
    const obs = apiUserInvitationGet$Json(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiUserInvitationGet$Json$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiUserInvitationGet$Json(params?: ApiUserInvitationGet$Json$Params, context?: HttpContext): Promise<Array<UserInvitation>> {
    const resp = this.apiUserInvitationGet$Json$Response(params, context);
    return resp.then((r: StrictHttpResponse<Array<UserInvitation>>): Array<UserInvitation> => r.body);
  }

  /** Path part for operation `apiUserInvitationPost()` */
  static readonly ApiUserInvitationPostPath = '/api/UserInvitation';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiUserInvitationPost$Plain()` instead.
   *
   * This method sends `application/*+json` and handles request body of type `application/*+json`.
   */
  apiUserInvitationPost$Plain$Response(params: ApiUserInvitationPost$Plain$Params, context?: HttpContext): Promise<StrictHttpResponse<InviteUserResponse>> {
    const obs = apiUserInvitationPost$Plain(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiUserInvitationPost$Plain$Response()` instead.
   *
   * This method sends `application/*+json` and handles request body of type `application/*+json`.
   */
  apiUserInvitationPost$Plain(params: ApiUserInvitationPost$Plain$Params, context?: HttpContext): Promise<InviteUserResponse> {
    const resp = this.apiUserInvitationPost$Plain$Response(params, context);
    return resp.then((r: StrictHttpResponse<InviteUserResponse>): InviteUserResponse => r.body);
  }

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiUserInvitationPost$Json()` instead.
   *
   * This method sends `application/*+json` and handles request body of type `application/*+json`.
   */
  apiUserInvitationPost$Json$Response(params: ApiUserInvitationPost$Json$Params, context?: HttpContext): Promise<StrictHttpResponse<InviteUserResponse>> {
    const obs = apiUserInvitationPost$Json(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiUserInvitationPost$Json$Response()` instead.
   *
   * This method sends `application/*+json` and handles request body of type `application/*+json`.
   */
  apiUserInvitationPost$Json(params: ApiUserInvitationPost$Json$Params, context?: HttpContext): Promise<InviteUserResponse> {
    const resp = this.apiUserInvitationPost$Json$Response(params, context);
    return resp.then((r: StrictHttpResponse<InviteUserResponse>): InviteUserResponse => r.body);
  }

  /** Path part for operation `apiUserInvitationIdArchivePost()` */
  static readonly ApiUserInvitationIdArchivePostPath = '/api/UserInvitation/{id}/archive';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiUserInvitationIdArchivePost()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiUserInvitationIdArchivePost$Response(params: ApiUserInvitationIdArchivePost$Params, context?: HttpContext): Promise<StrictHttpResponse<void>> {
    const obs = apiUserInvitationIdArchivePost(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiUserInvitationIdArchivePost$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiUserInvitationIdArchivePost(params: ApiUserInvitationIdArchivePost$Params, context?: HttpContext): Promise<void> {
    const resp = this.apiUserInvitationIdArchivePost$Response(params, context);
    return resp.then((r: StrictHttpResponse<void>): void => r.body);
  }

}
