/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { firstValueFrom } from 'rxjs';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { apiUserGet$Json } from '../fn/user/api-user-get-json';
import { ApiUserGet$Json$Params } from '../fn/user/api-user-get-json';
import { apiUserGet$Plain } from '../fn/user/api-user-get-plain';
import { ApiUserGet$Plain$Params } from '../fn/user/api-user-get-plain';
import { apiUserIdEnrichedGet$Json } from '../fn/user/api-user-id-enriched-get-json';
import { ApiUserIdEnrichedGet$Json$Params } from '../fn/user/api-user-id-enriched-get-json';
import { apiUserIdEnrichedGet$Plain } from '../fn/user/api-user-id-enriched-get-plain';
import { ApiUserIdEnrichedGet$Plain$Params } from '../fn/user/api-user-id-enriched-get-plain';
import { apiUserIdGet$Json } from '../fn/user/api-user-id-get-json';
import { ApiUserIdGet$Json$Params } from '../fn/user/api-user-id-get-json';
import { apiUserIdGet$Plain } from '../fn/user/api-user-id-get-plain';
import { ApiUserIdGet$Plain$Params } from '../fn/user/api-user-id-get-plain';
import { apiUserIdProfilePictureDelete$Json } from '../fn/user/api-user-id-profile-picture-delete-json';
import { ApiUserIdProfilePictureDelete$Json$Params } from '../fn/user/api-user-id-profile-picture-delete-json';
import { apiUserIdProfilePictureDelete$Plain } from '../fn/user/api-user-id-profile-picture-delete-plain';
import { ApiUserIdProfilePictureDelete$Plain$Params } from '../fn/user/api-user-id-profile-picture-delete-plain';
import { apiUserIdProfilePicturePost$Json } from '../fn/user/api-user-id-profile-picture-post-json';
import { ApiUserIdProfilePicturePost$Json$Params } from '../fn/user/api-user-id-profile-picture-post-json';
import { apiUserIdProfilePicturePost$Plain } from '../fn/user/api-user-id-profile-picture-post-plain';
import { ApiUserIdProfilePicturePost$Plain$Params } from '../fn/user/api-user-id-profile-picture-post-plain';
import { apiUserIdPut$Json } from '../fn/user/api-user-id-put-json';
import { ApiUserIdPut$Json$Params } from '../fn/user/api-user-id-put-json';
import { apiUserIdPut$Plain } from '../fn/user/api-user-id-put-plain';
import { ApiUserIdPut$Plain$Params } from '../fn/user/api-user-id-put-plain';
import { apiUserIdRolesGet$Json } from '../fn/user/api-user-id-roles-get-json';
import { ApiUserIdRolesGet$Json$Params } from '../fn/user/api-user-id-roles-get-json';
import { apiUserIdRolesGet$Plain } from '../fn/user/api-user-id-roles-get-plain';
import { ApiUserIdRolesGet$Plain$Params } from '../fn/user/api-user-id-roles-get-plain';
import { apiUserIdRolesRoleIdDelete } from '../fn/user/api-user-id-roles-role-id-delete';
import { ApiUserIdRolesRoleIdDelete$Params } from '../fn/user/api-user-id-roles-role-id-delete';
import { apiUserIdRolesRoleIdPost } from '../fn/user/api-user-id-roles-role-id-post';
import { ApiUserIdRolesRoleIdPost$Params } from '../fn/user/api-user-id-roles-role-id-post';
import { apiUserIdTeamsGet$Json } from '../fn/user/api-user-id-teams-get-json';
import { ApiUserIdTeamsGet$Json$Params } from '../fn/user/api-user-id-teams-get-json';
import { apiUserIdTeamsGet$Plain } from '../fn/user/api-user-id-teams-get-plain';
import { ApiUserIdTeamsGet$Plain$Params } from '../fn/user/api-user-id-teams-get-plain';
import { apiUserIdTeamsTeamIdDelete } from '../fn/user/api-user-id-teams-team-id-delete';
import { ApiUserIdTeamsTeamIdDelete$Params } from '../fn/user/api-user-id-teams-team-id-delete';
import { apiUserIdTeamsTeamIdPost } from '../fn/user/api-user-id-teams-team-id-post';
import { ApiUserIdTeamsTeamIdPost$Params } from '../fn/user/api-user-id-teams-team-id-post';
import { apiUserMePermissionsGet$Json } from '../fn/user/api-user-me-permissions-get-json';
import { ApiUserMePermissionsGet$Json$Params } from '../fn/user/api-user-me-permissions-get-json';
import { apiUserMePermissionsGet$Plain } from '../fn/user/api-user-me-permissions-get-plain';
import { ApiUserMePermissionsGet$Plain$Params } from '../fn/user/api-user-me-permissions-get-plain';
import { apiUserPost$Json } from '../fn/user/api-user-post-json';
import { ApiUserPost$Json$Params } from '../fn/user/api-user-post-json';
import { apiUserPost$Plain } from '../fn/user/api-user-post-plain';
import { ApiUserPost$Plain$Params } from '../fn/user/api-user-post-plain';
import { EnrichedUserDto } from '../models/enriched-user-dto';
import { Role } from '../models/role';
import { RolePermissionDto } from '../models/role-permission-dto';
import { Team } from '../models/team';
import { User } from '../models/user';

@Injectable({ providedIn: 'root' })
export class UserService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `apiUserGet()` */
  static readonly ApiUserGetPath = '/api/User';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiUserGet$Plain()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiUserGet$Plain$Response(params?: ApiUserGet$Plain$Params, context?: HttpContext): Promise<StrictHttpResponse<Array<User>>> {
    const obs = apiUserGet$Plain(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiUserGet$Plain$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiUserGet$Plain(params?: ApiUserGet$Plain$Params, context?: HttpContext): Promise<Array<User>> {
    const resp = this.apiUserGet$Plain$Response(params, context);
    return resp.then((r: StrictHttpResponse<Array<User>>): Array<User> => r.body);
  }

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiUserGet$Json()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiUserGet$Json$Response(params?: ApiUserGet$Json$Params, context?: HttpContext): Promise<StrictHttpResponse<Array<User>>> {
    const obs = apiUserGet$Json(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiUserGet$Json$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiUserGet$Json(params?: ApiUserGet$Json$Params, context?: HttpContext): Promise<Array<User>> {
    const resp = this.apiUserGet$Json$Response(params, context);
    return resp.then((r: StrictHttpResponse<Array<User>>): Array<User> => r.body);
  }

  /** Path part for operation `apiUserPost()` */
  static readonly ApiUserPostPath = '/api/User';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiUserPost$Plain()` instead.
   *
   * This method sends `application/*+json` and handles request body of type `application/*+json`.
   */
  apiUserPost$Plain$Response(params: ApiUserPost$Plain$Params, context?: HttpContext): Promise<StrictHttpResponse<User>> {
    const obs = apiUserPost$Plain(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiUserPost$Plain$Response()` instead.
   *
   * This method sends `application/*+json` and handles request body of type `application/*+json`.
   */
  apiUserPost$Plain(params: ApiUserPost$Plain$Params, context?: HttpContext): Promise<User> {
    const resp = this.apiUserPost$Plain$Response(params, context);
    return resp.then((r: StrictHttpResponse<User>): User => r.body);
  }

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiUserPost$Json()` instead.
   *
   * This method sends `application/*+json` and handles request body of type `application/*+json`.
   */
  apiUserPost$Json$Response(params: ApiUserPost$Json$Params, context?: HttpContext): Promise<StrictHttpResponse<User>> {
    const obs = apiUserPost$Json(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiUserPost$Json$Response()` instead.
   *
   * This method sends `application/*+json` and handles request body of type `application/*+json`.
   */
  apiUserPost$Json(params: ApiUserPost$Json$Params, context?: HttpContext): Promise<User> {
    const resp = this.apiUserPost$Json$Response(params, context);
    return resp.then((r: StrictHttpResponse<User>): User => r.body);
  }

  /** Path part for operation `apiUserIdGet()` */
  static readonly ApiUserIdGetPath = '/api/User/{id}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiUserIdGet$Plain()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiUserIdGet$Plain$Response(params: ApiUserIdGet$Plain$Params, context?: HttpContext): Promise<StrictHttpResponse<User>> {
    const obs = apiUserIdGet$Plain(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiUserIdGet$Plain$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiUserIdGet$Plain(params: ApiUserIdGet$Plain$Params, context?: HttpContext): Promise<User> {
    const resp = this.apiUserIdGet$Plain$Response(params, context);
    return resp.then((r: StrictHttpResponse<User>): User => r.body);
  }

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiUserIdGet$Json()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiUserIdGet$Json$Response(params: ApiUserIdGet$Json$Params, context?: HttpContext): Promise<StrictHttpResponse<User>> {
    const obs = apiUserIdGet$Json(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiUserIdGet$Json$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiUserIdGet$Json(params: ApiUserIdGet$Json$Params, context?: HttpContext): Promise<User> {
    const resp = this.apiUserIdGet$Json$Response(params, context);
    return resp.then((r: StrictHttpResponse<User>): User => r.body);
  }

  /** Path part for operation `apiUserIdPut()` */
  static readonly ApiUserIdPutPath = '/api/User/{id}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiUserIdPut$Plain()` instead.
   *
   * This method sends `application/*+json` and handles request body of type `application/*+json`.
   */
  apiUserIdPut$Plain$Response(params: ApiUserIdPut$Plain$Params, context?: HttpContext): Promise<StrictHttpResponse<User>> {
    const obs = apiUserIdPut$Plain(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiUserIdPut$Plain$Response()` instead.
   *
   * This method sends `application/*+json` and handles request body of type `application/*+json`.
   */
  apiUserIdPut$Plain(params: ApiUserIdPut$Plain$Params, context?: HttpContext): Promise<User> {
    const resp = this.apiUserIdPut$Plain$Response(params, context);
    return resp.then((r: StrictHttpResponse<User>): User => r.body);
  }

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiUserIdPut$Json()` instead.
   *
   * This method sends `application/*+json` and handles request body of type `application/*+json`.
   */
  apiUserIdPut$Json$Response(params: ApiUserIdPut$Json$Params, context?: HttpContext): Promise<StrictHttpResponse<User>> {
    const obs = apiUserIdPut$Json(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiUserIdPut$Json$Response()` instead.
   *
   * This method sends `application/*+json` and handles request body of type `application/*+json`.
   */
  apiUserIdPut$Json(params: ApiUserIdPut$Json$Params, context?: HttpContext): Promise<User> {
    const resp = this.apiUserIdPut$Json$Response(params, context);
    return resp.then((r: StrictHttpResponse<User>): User => r.body);
  }

  /** Path part for operation `apiUserIdEnrichedGet()` */
  static readonly ApiUserIdEnrichedGetPath = '/api/User/{id}/enriched';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiUserIdEnrichedGet$Plain()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiUserIdEnrichedGet$Plain$Response(params: ApiUserIdEnrichedGet$Plain$Params, context?: HttpContext): Promise<StrictHttpResponse<EnrichedUserDto>> {
    const obs = apiUserIdEnrichedGet$Plain(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiUserIdEnrichedGet$Plain$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiUserIdEnrichedGet$Plain(params: ApiUserIdEnrichedGet$Plain$Params, context?: HttpContext): Promise<EnrichedUserDto> {
    const resp = this.apiUserIdEnrichedGet$Plain$Response(params, context);
    return resp.then((r: StrictHttpResponse<EnrichedUserDto>): EnrichedUserDto => r.body);
  }

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiUserIdEnrichedGet$Json()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiUserIdEnrichedGet$Json$Response(params: ApiUserIdEnrichedGet$Json$Params, context?: HttpContext): Promise<StrictHttpResponse<EnrichedUserDto>> {
    const obs = apiUserIdEnrichedGet$Json(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiUserIdEnrichedGet$Json$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiUserIdEnrichedGet$Json(params: ApiUserIdEnrichedGet$Json$Params, context?: HttpContext): Promise<EnrichedUserDto> {
    const resp = this.apiUserIdEnrichedGet$Json$Response(params, context);
    return resp.then((r: StrictHttpResponse<EnrichedUserDto>): EnrichedUserDto => r.body);
  }

  /** Path part for operation `apiUserIdRolesGet()` */
  static readonly ApiUserIdRolesGetPath = '/api/User/{id}/roles';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiUserIdRolesGet$Plain()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiUserIdRolesGet$Plain$Response(params: ApiUserIdRolesGet$Plain$Params, context?: HttpContext): Promise<StrictHttpResponse<Array<Role>>> {
    const obs = apiUserIdRolesGet$Plain(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiUserIdRolesGet$Plain$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiUserIdRolesGet$Plain(params: ApiUserIdRolesGet$Plain$Params, context?: HttpContext): Promise<Array<Role>> {
    const resp = this.apiUserIdRolesGet$Plain$Response(params, context);
    return resp.then((r: StrictHttpResponse<Array<Role>>): Array<Role> => r.body);
  }

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiUserIdRolesGet$Json()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiUserIdRolesGet$Json$Response(params: ApiUserIdRolesGet$Json$Params, context?: HttpContext): Promise<StrictHttpResponse<Array<Role>>> {
    const obs = apiUserIdRolesGet$Json(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiUserIdRolesGet$Json$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiUserIdRolesGet$Json(params: ApiUserIdRolesGet$Json$Params, context?: HttpContext): Promise<Array<Role>> {
    const resp = this.apiUserIdRolesGet$Json$Response(params, context);
    return resp.then((r: StrictHttpResponse<Array<Role>>): Array<Role> => r.body);
  }

  /** Path part for operation `apiUserIdRolesRoleIdPost()` */
  static readonly ApiUserIdRolesRoleIdPostPath = '/api/User/{id}/roles/{roleId}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiUserIdRolesRoleIdPost()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiUserIdRolesRoleIdPost$Response(params: ApiUserIdRolesRoleIdPost$Params, context?: HttpContext): Promise<StrictHttpResponse<void>> {
    const obs = apiUserIdRolesRoleIdPost(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiUserIdRolesRoleIdPost$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiUserIdRolesRoleIdPost(params: ApiUserIdRolesRoleIdPost$Params, context?: HttpContext): Promise<void> {
    const resp = this.apiUserIdRolesRoleIdPost$Response(params, context);
    return resp.then((r: StrictHttpResponse<void>): void => r.body);
  }

  /** Path part for operation `apiUserIdRolesRoleIdDelete()` */
  static readonly ApiUserIdRolesRoleIdDeletePath = '/api/User/{id}/roles/{roleId}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiUserIdRolesRoleIdDelete()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiUserIdRolesRoleIdDelete$Response(params: ApiUserIdRolesRoleIdDelete$Params, context?: HttpContext): Promise<StrictHttpResponse<void>> {
    const obs = apiUserIdRolesRoleIdDelete(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiUserIdRolesRoleIdDelete$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiUserIdRolesRoleIdDelete(params: ApiUserIdRolesRoleIdDelete$Params, context?: HttpContext): Promise<void> {
    const resp = this.apiUserIdRolesRoleIdDelete$Response(params, context);
    return resp.then((r: StrictHttpResponse<void>): void => r.body);
  }

  /** Path part for operation `apiUserIdTeamsGet()` */
  static readonly ApiUserIdTeamsGetPath = '/api/User/{id}/teams';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiUserIdTeamsGet$Plain()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiUserIdTeamsGet$Plain$Response(params: ApiUserIdTeamsGet$Plain$Params, context?: HttpContext): Promise<StrictHttpResponse<Array<Team>>> {
    const obs = apiUserIdTeamsGet$Plain(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiUserIdTeamsGet$Plain$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiUserIdTeamsGet$Plain(params: ApiUserIdTeamsGet$Plain$Params, context?: HttpContext): Promise<Array<Team>> {
    const resp = this.apiUserIdTeamsGet$Plain$Response(params, context);
    return resp.then((r: StrictHttpResponse<Array<Team>>): Array<Team> => r.body);
  }

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiUserIdTeamsGet$Json()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiUserIdTeamsGet$Json$Response(params: ApiUserIdTeamsGet$Json$Params, context?: HttpContext): Promise<StrictHttpResponse<Array<Team>>> {
    const obs = apiUserIdTeamsGet$Json(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiUserIdTeamsGet$Json$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiUserIdTeamsGet$Json(params: ApiUserIdTeamsGet$Json$Params, context?: HttpContext): Promise<Array<Team>> {
    const resp = this.apiUserIdTeamsGet$Json$Response(params, context);
    return resp.then((r: StrictHttpResponse<Array<Team>>): Array<Team> => r.body);
  }

  /** Path part for operation `apiUserIdTeamsTeamIdPost()` */
  static readonly ApiUserIdTeamsTeamIdPostPath = '/api/User/{id}/teams/{teamId}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiUserIdTeamsTeamIdPost()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiUserIdTeamsTeamIdPost$Response(params: ApiUserIdTeamsTeamIdPost$Params, context?: HttpContext): Promise<StrictHttpResponse<void>> {
    const obs = apiUserIdTeamsTeamIdPost(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiUserIdTeamsTeamIdPost$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiUserIdTeamsTeamIdPost(params: ApiUserIdTeamsTeamIdPost$Params, context?: HttpContext): Promise<void> {
    const resp = this.apiUserIdTeamsTeamIdPost$Response(params, context);
    return resp.then((r: StrictHttpResponse<void>): void => r.body);
  }

  /** Path part for operation `apiUserIdTeamsTeamIdDelete()` */
  static readonly ApiUserIdTeamsTeamIdDeletePath = '/api/User/{id}/teams/{teamId}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiUserIdTeamsTeamIdDelete()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiUserIdTeamsTeamIdDelete$Response(params: ApiUserIdTeamsTeamIdDelete$Params, context?: HttpContext): Promise<StrictHttpResponse<void>> {
    const obs = apiUserIdTeamsTeamIdDelete(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiUserIdTeamsTeamIdDelete$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiUserIdTeamsTeamIdDelete(params: ApiUserIdTeamsTeamIdDelete$Params, context?: HttpContext): Promise<void> {
    const resp = this.apiUserIdTeamsTeamIdDelete$Response(params, context);
    return resp.then((r: StrictHttpResponse<void>): void => r.body);
  }

  /** Path part for operation `apiUserMePermissionsGet()` */
  static readonly ApiUserMePermissionsGetPath = '/api/User/me/permissions';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiUserMePermissionsGet$Plain()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiUserMePermissionsGet$Plain$Response(params?: ApiUserMePermissionsGet$Plain$Params, context?: HttpContext): Promise<StrictHttpResponse<Array<RolePermissionDto>>> {
    const obs = apiUserMePermissionsGet$Plain(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiUserMePermissionsGet$Plain$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiUserMePermissionsGet$Plain(params?: ApiUserMePermissionsGet$Plain$Params, context?: HttpContext): Promise<Array<RolePermissionDto>> {
    const resp = this.apiUserMePermissionsGet$Plain$Response(params, context);
    return resp.then((r: StrictHttpResponse<Array<RolePermissionDto>>): Array<RolePermissionDto> => r.body);
  }

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiUserMePermissionsGet$Json()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiUserMePermissionsGet$Json$Response(params?: ApiUserMePermissionsGet$Json$Params, context?: HttpContext): Promise<StrictHttpResponse<Array<RolePermissionDto>>> {
    const obs = apiUserMePermissionsGet$Json(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiUserMePermissionsGet$Json$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiUserMePermissionsGet$Json(params?: ApiUserMePermissionsGet$Json$Params, context?: HttpContext): Promise<Array<RolePermissionDto>> {
    const resp = this.apiUserMePermissionsGet$Json$Response(params, context);
    return resp.then((r: StrictHttpResponse<Array<RolePermissionDto>>): Array<RolePermissionDto> => r.body);
  }

  /** Path part for operation `apiUserIdProfilePicturePost()` */
  static readonly ApiUserIdProfilePicturePostPath = '/api/User/{id}/profile-picture';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiUserIdProfilePicturePost$Plain()` instead.
   *
   * This method sends `multipart/form-data` and handles request body of type `multipart/form-data`.
   */
  apiUserIdProfilePicturePost$Plain$Response(params: ApiUserIdProfilePicturePost$Plain$Params, context?: HttpContext): Promise<StrictHttpResponse<User>> {
    const obs = apiUserIdProfilePicturePost$Plain(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiUserIdProfilePicturePost$Plain$Response()` instead.
   *
   * This method sends `multipart/form-data` and handles request body of type `multipart/form-data`.
   */
  apiUserIdProfilePicturePost$Plain(params: ApiUserIdProfilePicturePost$Plain$Params, context?: HttpContext): Promise<User> {
    const resp = this.apiUserIdProfilePicturePost$Plain$Response(params, context);
    return resp.then((r: StrictHttpResponse<User>): User => r.body);
  }

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiUserIdProfilePicturePost$Json()` instead.
   *
   * This method sends `multipart/form-data` and handles request body of type `multipart/form-data`.
   */
  apiUserIdProfilePicturePost$Json$Response(params: ApiUserIdProfilePicturePost$Json$Params, context?: HttpContext): Promise<StrictHttpResponse<User>> {
    const obs = apiUserIdProfilePicturePost$Json(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiUserIdProfilePicturePost$Json$Response()` instead.
   *
   * This method sends `multipart/form-data` and handles request body of type `multipart/form-data`.
   */
  apiUserIdProfilePicturePost$Json(params: ApiUserIdProfilePicturePost$Json$Params, context?: HttpContext): Promise<User> {
    const resp = this.apiUserIdProfilePicturePost$Json$Response(params, context);
    return resp.then((r: StrictHttpResponse<User>): User => r.body);
  }

  /** Path part for operation `apiUserIdProfilePictureDelete()` */
  static readonly ApiUserIdProfilePictureDeletePath = '/api/User/{id}/profile-picture';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiUserIdProfilePictureDelete$Plain()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiUserIdProfilePictureDelete$Plain$Response(params: ApiUserIdProfilePictureDelete$Plain$Params, context?: HttpContext): Promise<StrictHttpResponse<User>> {
    const obs = apiUserIdProfilePictureDelete$Plain(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiUserIdProfilePictureDelete$Plain$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiUserIdProfilePictureDelete$Plain(params: ApiUserIdProfilePictureDelete$Plain$Params, context?: HttpContext): Promise<User> {
    const resp = this.apiUserIdProfilePictureDelete$Plain$Response(params, context);
    return resp.then((r: StrictHttpResponse<User>): User => r.body);
  }

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiUserIdProfilePictureDelete$Json()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiUserIdProfilePictureDelete$Json$Response(params: ApiUserIdProfilePictureDelete$Json$Params, context?: HttpContext): Promise<StrictHttpResponse<User>> {
    const obs = apiUserIdProfilePictureDelete$Json(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiUserIdProfilePictureDelete$Json$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiUserIdProfilePictureDelete$Json(params: ApiUserIdProfilePictureDelete$Json$Params, context?: HttpContext): Promise<User> {
    const resp = this.apiUserIdProfilePictureDelete$Json$Response(params, context);
    return resp.then((r: StrictHttpResponse<User>): User => r.body);
  }

}
