/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { firstValueFrom } from 'rxjs';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { apiWorkScheduleGet$Json } from '../fn/work-schedule/api-work-schedule-get-json';
import { ApiWorkScheduleGet$Json$Params } from '../fn/work-schedule/api-work-schedule-get-json';
import { apiWorkScheduleGet$Plain } from '../fn/work-schedule/api-work-schedule-get-plain';
import { ApiWorkScheduleGet$Plain$Params } from '../fn/work-schedule/api-work-schedule-get-plain';
import { apiWorkScheduleIdGet$Json } from '../fn/work-schedule/api-work-schedule-id-get-json';
import { ApiWorkScheduleIdGet$Json$Params } from '../fn/work-schedule/api-work-schedule-id-get-json';
import { apiWorkScheduleIdGet$Plain } from '../fn/work-schedule/api-work-schedule-id-get-plain';
import { ApiWorkScheduleIdGet$Plain$Params } from '../fn/work-schedule/api-work-schedule-id-get-plain';
import { apiWorkSchedulePost$Json } from '../fn/work-schedule/api-work-schedule-post-json';
import { ApiWorkSchedulePost$Json$Params } from '../fn/work-schedule/api-work-schedule-post-json';
import { apiWorkSchedulePost$Plain } from '../fn/work-schedule/api-work-schedule-post-plain';
import { ApiWorkSchedulePost$Plain$Params } from '../fn/work-schedule/api-work-schedule-post-plain';
import { WorkSchedule } from '../models/work-schedule';

@Injectable({ providedIn: 'root' })
export class WorkScheduleService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `apiWorkScheduleGet()` */
  static readonly ApiWorkScheduleGetPath = '/api/WorkSchedule';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiWorkScheduleGet$Plain()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiWorkScheduleGet$Plain$Response(params?: ApiWorkScheduleGet$Plain$Params, context?: HttpContext): Promise<StrictHttpResponse<Array<WorkSchedule>>> {
    const obs = apiWorkScheduleGet$Plain(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiWorkScheduleGet$Plain$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiWorkScheduleGet$Plain(params?: ApiWorkScheduleGet$Plain$Params, context?: HttpContext): Promise<Array<WorkSchedule>> {
    const resp = this.apiWorkScheduleGet$Plain$Response(params, context);
    return resp.then((r: StrictHttpResponse<Array<WorkSchedule>>): Array<WorkSchedule> => r.body);
  }

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiWorkScheduleGet$Json()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiWorkScheduleGet$Json$Response(params?: ApiWorkScheduleGet$Json$Params, context?: HttpContext): Promise<StrictHttpResponse<Array<WorkSchedule>>> {
    const obs = apiWorkScheduleGet$Json(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiWorkScheduleGet$Json$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiWorkScheduleGet$Json(params?: ApiWorkScheduleGet$Json$Params, context?: HttpContext): Promise<Array<WorkSchedule>> {
    const resp = this.apiWorkScheduleGet$Json$Response(params, context);
    return resp.then((r: StrictHttpResponse<Array<WorkSchedule>>): Array<WorkSchedule> => r.body);
  }

  /** Path part for operation `apiWorkSchedulePost()` */
  static readonly ApiWorkSchedulePostPath = '/api/WorkSchedule';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiWorkSchedulePost$Plain()` instead.
   *
   * This method sends `application/*+json` and handles request body of type `application/*+json`.
   */
  apiWorkSchedulePost$Plain$Response(params: ApiWorkSchedulePost$Plain$Params, context?: HttpContext): Promise<StrictHttpResponse<WorkSchedule>> {
    const obs = apiWorkSchedulePost$Plain(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiWorkSchedulePost$Plain$Response()` instead.
   *
   * This method sends `application/*+json` and handles request body of type `application/*+json`.
   */
  apiWorkSchedulePost$Plain(params: ApiWorkSchedulePost$Plain$Params, context?: HttpContext): Promise<WorkSchedule> {
    const resp = this.apiWorkSchedulePost$Plain$Response(params, context);
    return resp.then((r: StrictHttpResponse<WorkSchedule>): WorkSchedule => r.body);
  }

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiWorkSchedulePost$Json()` instead.
   *
   * This method sends `application/*+json` and handles request body of type `application/*+json`.
   */
  apiWorkSchedulePost$Json$Response(params: ApiWorkSchedulePost$Json$Params, context?: HttpContext): Promise<StrictHttpResponse<WorkSchedule>> {
    const obs = apiWorkSchedulePost$Json(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiWorkSchedulePost$Json$Response()` instead.
   *
   * This method sends `application/*+json` and handles request body of type `application/*+json`.
   */
  apiWorkSchedulePost$Json(params: ApiWorkSchedulePost$Json$Params, context?: HttpContext): Promise<WorkSchedule> {
    const resp = this.apiWorkSchedulePost$Json$Response(params, context);
    return resp.then((r: StrictHttpResponse<WorkSchedule>): WorkSchedule => r.body);
  }

  /** Path part for operation `apiWorkScheduleIdGet()` */
  static readonly ApiWorkScheduleIdGetPath = '/api/WorkSchedule/{id}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiWorkScheduleIdGet$Plain()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiWorkScheduleIdGet$Plain$Response(params: ApiWorkScheduleIdGet$Plain$Params, context?: HttpContext): Promise<StrictHttpResponse<WorkSchedule>> {
    const obs = apiWorkScheduleIdGet$Plain(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiWorkScheduleIdGet$Plain$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiWorkScheduleIdGet$Plain(params: ApiWorkScheduleIdGet$Plain$Params, context?: HttpContext): Promise<WorkSchedule> {
    const resp = this.apiWorkScheduleIdGet$Plain$Response(params, context);
    return resp.then((r: StrictHttpResponse<WorkSchedule>): WorkSchedule => r.body);
  }

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiWorkScheduleIdGet$Json()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiWorkScheduleIdGet$Json$Response(params: ApiWorkScheduleIdGet$Json$Params, context?: HttpContext): Promise<StrictHttpResponse<WorkSchedule>> {
    const obs = apiWorkScheduleIdGet$Json(this.http, this.rootUrl, params, context);
    return firstValueFrom(obs);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiWorkScheduleIdGet$Json$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiWorkScheduleIdGet$Json(params: ApiWorkScheduleIdGet$Json$Params, context?: HttpContext): Promise<WorkSchedule> {
    const resp = this.apiWorkScheduleIdGet$Json$Response(params, context);
    return resp.then((r: StrictHttpResponse<WorkSchedule>): WorkSchedule => r.body);
  }

}
