/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { LeaveBalance } from '../../models/leave-balance';

export interface ApiLeaveBalancePost$Json$Params {
      body: LeaveBalance
}

export function apiLeaveBalancePost$Json(http: HttpClient, rootUrl: string, params: ApiLeaveBalancePost$Json$Params, context?: HttpContext): Observable<StrictHttpResponse<LeaveBalance>> {
  const rb = new RequestBuilder(rootUrl, apiLeaveBalancePost$Json.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/*+json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'text/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<LeaveBalance>;
    })
  );
}

apiLeaveBalancePost$Json.PATH = '/api/LeaveBalance';
