/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { AppSettingsResponse } from '../../models/app-settings-response';

export interface ApiAppSettingsGet$Plain$Params {
}

export function apiAppSettingsGet$Plain(http: HttpClient, rootUrl: string, params?: ApiAppSettingsGet$Plain$Params, context?: HttpContext): Observable<StrictHttpResponse<AppSettingsResponse>> {
  const rb = new RequestBuilder(rootUrl, apiAppSettingsGet$Plain.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'text', accept: 'text/plain', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<AppSettingsResponse>;
    })
  );
}

apiAppSettingsGet$Plain.PATH = '/api/AppSettings';
