/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { RegisterRequest } from '../../models/register-request';
import { RegisterResponse } from '../../models/register-response';

export interface ApiAuthRegisterPost$Plain$Params {
      body: RegisterRequest
}

export function apiAuthRegisterPost$Plain(http: HttpClient, rootUrl: string, params: ApiAuthRegisterPost$Plain$Params, context?: HttpContext): Observable<StrictHttpResponse<RegisterResponse>> {
  const rb = new RequestBuilder(rootUrl, apiAuthRegisterPost$Plain.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/*+json');
  }

  return http.request(
    rb.build({ responseType: 'text', accept: 'text/plain', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<RegisterResponse>;
    })
  );
}

apiAuthRegisterPost$Plain.PATH = '/api/Auth/register';
