/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { TimeEntryAuditLog } from '../../models/time-entry-audit-log';

export interface ApiTimeEntryAuditLogIdGet$Plain$Params {
  id: (number | string);
}

export function apiTimeEntryAuditLogIdGet$Plain(http: HttpClient, rootUrl: string, params: ApiTimeEntryAuditLogIdGet$Plain$Params, context?: HttpContext): Observable<StrictHttpResponse<TimeEntryAuditLog>> {
  const rb = new RequestBuilder(rootUrl, apiTimeEntryAuditLogIdGet$Plain.PATH, 'get');
  if (params) {
    rb.path('id', params.id, {});
  }

  return http.request(
    rb.build({ responseType: 'text', accept: 'text/plain', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<TimeEntryAuditLog>;
    })
  );
}

apiTimeEntryAuditLogIdGet$Plain.PATH = '/api/TimeEntryAuditLog/{id}';
