/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { LeaveRequest } from '../../models/leave-request';

export interface ApiLeaveRequestGet$Json$Params {
}

export function apiLeaveRequestGet$Json(http: HttpClient, rootUrl: string, params?: ApiLeaveRequestGet$Json$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<LeaveRequest>>> {
  const rb = new RequestBuilder(rootUrl, apiLeaveRequestGet$Json.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'text/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<LeaveRequest>>;
    })
  );
}

apiLeaveRequestGet$Json.PATH = '/api/LeaveRequest';
